// Code generated by ent, DO NOT EDIT.

package r2webdavsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the r2webdavsetting type in the database.
	Label = "r2web_dav_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldBucketName holds the string denoting the bucket_name field in the database.
	FieldBucketName = "bucket_name"
	// FieldJurisdiction holds the string denoting the jurisdiction field in the database.
	FieldJurisdiction = "jurisdiction"
	// FieldWebdavUsername holds the string denoting the webdav_username field in the database.
	FieldWebdavUsername = "webdav_username"
	// FieldWebdavPasswordHash holds the string denoting the webdav_password_hash field in the database.
	FieldWebdavPasswordHash = "webdav_password_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the r2webdavsetting in the database.
	Table = "r2web_dav_settings"
)

// Columns holds all SQL columns for r2webdavsetting fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldEnabled,
	FieldAccountID,
	FieldBucketName,
	FieldJurisdiction,
	FieldWebdavUsername,
	FieldWebdavPasswordHash,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultBucketName holds the default value on creation for the "bucket_name" field.
	DefaultBucketName string
	// DefaultJurisdiction holds the default value on creation for the "jurisdiction" field.
	DefaultJurisdiction string
	// DefaultWebdavUsername holds the default value on creation for the "webdav_username" field.
	DefaultWebdavUsername string
	// DefaultWebdavPasswordHash holds the default value on creation for the "webdav_password_hash" field.
	DefaultWebdavPasswordHash string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the R2WebDAVSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByBucketName orders the results by the bucket_name field.
func ByBucketName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketName, opts...).ToFunc()
}

// ByJurisdiction orders the results by the jurisdiction field.
func ByJurisdiction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJurisdiction, opts...).ToFunc()
}

// ByWebdavUsername orders the results by the webdav_username field.
func ByWebdavUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavUsername, opts...).ToFunc()
}

// ByWebdavPasswordHash orders the results by the webdav_password_hash field.
func ByWebdavPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavPasswordHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
