// Code generated by ent, DO NOT EDIT.

package r2webdavsetting

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldKey, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldEnabled, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldAccountID, v))
}

// BucketName applies equality check predicate on the "bucket_name" field. It's identical to BucketNameEQ.
func BucketName(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldBucketName, v))
}

// Jurisdiction applies equality check predicate on the "jurisdiction" field. It's identical to JurisdictionEQ.
func Jurisdiction(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldJurisdiction, v))
}

// WebdavUsername applies equality check predicate on the "webdav_username" field. It's identical to WebdavUsernameEQ.
func WebdavUsername(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldWebdavUsername, v))
}

// WebdavPasswordHash applies equality check predicate on the "webdav_password_hash" field. It's identical to WebdavPasswordHashEQ.
func WebdavPasswordHash(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldWebdavPasswordHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContainsFold(FieldKey, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldEnabled, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContainsFold(FieldAccountID, v))
}

// BucketNameEQ applies the EQ predicate on the "bucket_name" field.
func BucketNameEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldBucketName, v))
}

// BucketNameNEQ applies the NEQ predicate on the "bucket_name" field.
func BucketNameNEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldBucketName, v))
}

// BucketNameIn applies the In predicate on the "bucket_name" field.
func BucketNameIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldBucketName, vs...))
}

// BucketNameNotIn applies the NotIn predicate on the "bucket_name" field.
func BucketNameNotIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldBucketName, vs...))
}

// BucketNameGT applies the GT predicate on the "bucket_name" field.
func BucketNameGT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldBucketName, v))
}

// BucketNameGTE applies the GTE predicate on the "bucket_name" field.
func BucketNameGTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldBucketName, v))
}

// BucketNameLT applies the LT predicate on the "bucket_name" field.
func BucketNameLT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldBucketName, v))
}

// BucketNameLTE applies the LTE predicate on the "bucket_name" field.
func BucketNameLTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldBucketName, v))
}

// BucketNameContains applies the Contains predicate on the "bucket_name" field.
func BucketNameContains(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContains(FieldBucketName, v))
}

// BucketNameHasPrefix applies the HasPrefix predicate on the "bucket_name" field.
func BucketNameHasPrefix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasPrefix(FieldBucketName, v))
}

// BucketNameHasSuffix applies the HasSuffix predicate on the "bucket_name" field.
func BucketNameHasSuffix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasSuffix(FieldBucketName, v))
}

// BucketNameEqualFold applies the EqualFold predicate on the "bucket_name" field.
func BucketNameEqualFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEqualFold(FieldBucketName, v))
}

// BucketNameContainsFold applies the ContainsFold predicate on the "bucket_name" field.
func BucketNameContainsFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContainsFold(FieldBucketName, v))
}

// JurisdictionEQ applies the EQ predicate on the "jurisdiction" field.
func JurisdictionEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldJurisdiction, v))
}

// JurisdictionNEQ applies the NEQ predicate on the "jurisdiction" field.
func JurisdictionNEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldJurisdiction, v))
}

// JurisdictionIn applies the In predicate on the "jurisdiction" field.
func JurisdictionIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldJurisdiction, vs...))
}

// JurisdictionNotIn applies the NotIn predicate on the "jurisdiction" field.
func JurisdictionNotIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldJurisdiction, vs...))
}

// JurisdictionGT applies the GT predicate on the "jurisdiction" field.
func JurisdictionGT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldJurisdiction, v))
}

// JurisdictionGTE applies the GTE predicate on the "jurisdiction" field.
func JurisdictionGTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldJurisdiction, v))
}

// JurisdictionLT applies the LT predicate on the "jurisdiction" field.
func JurisdictionLT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldJurisdiction, v))
}

// JurisdictionLTE applies the LTE predicate on the "jurisdiction" field.
func JurisdictionLTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldJurisdiction, v))
}

// JurisdictionContains applies the Contains predicate on the "jurisdiction" field.
func JurisdictionContains(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContains(FieldJurisdiction, v))
}

// JurisdictionHasPrefix applies the HasPrefix predicate on the "jurisdiction" field.
func JurisdictionHasPrefix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasPrefix(FieldJurisdiction, v))
}

// JurisdictionHasSuffix applies the HasSuffix predicate on the "jurisdiction" field.
func JurisdictionHasSuffix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasSuffix(FieldJurisdiction, v))
}

// JurisdictionEqualFold applies the EqualFold predicate on the "jurisdiction" field.
func JurisdictionEqualFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEqualFold(FieldJurisdiction, v))
}

// JurisdictionContainsFold applies the ContainsFold predicate on the "jurisdiction" field.
func JurisdictionContainsFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContainsFold(FieldJurisdiction, v))
}

// WebdavUsernameEQ applies the EQ predicate on the "webdav_username" field.
func WebdavUsernameEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldWebdavUsername, v))
}

// WebdavUsernameNEQ applies the NEQ predicate on the "webdav_username" field.
func WebdavUsernameNEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldWebdavUsername, v))
}

// WebdavUsernameIn applies the In predicate on the "webdav_username" field.
func WebdavUsernameIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldWebdavUsername, vs...))
}

// WebdavUsernameNotIn applies the NotIn predicate on the "webdav_username" field.
func WebdavUsernameNotIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldWebdavUsername, vs...))
}

// WebdavUsernameGT applies the GT predicate on the "webdav_username" field.
func WebdavUsernameGT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldWebdavUsername, v))
}

// WebdavUsernameGTE applies the GTE predicate on the "webdav_username" field.
func WebdavUsernameGTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldWebdavUsername, v))
}

// WebdavUsernameLT applies the LT predicate on the "webdav_username" field.
func WebdavUsernameLT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldWebdavUsername, v))
}

// WebdavUsernameLTE applies the LTE predicate on the "webdav_username" field.
func WebdavUsernameLTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldWebdavUsername, v))
}

// WebdavUsernameContains applies the Contains predicate on the "webdav_username" field.
func WebdavUsernameContains(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContains(FieldWebdavUsername, v))
}

// WebdavUsernameHasPrefix applies the HasPrefix predicate on the "webdav_username" field.
func WebdavUsernameHasPrefix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasPrefix(FieldWebdavUsername, v))
}

// WebdavUsernameHasSuffix applies the HasSuffix predicate on the "webdav_username" field.
func WebdavUsernameHasSuffix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasSuffix(FieldWebdavUsername, v))
}

// WebdavUsernameEqualFold applies the EqualFold predicate on the "webdav_username" field.
func WebdavUsernameEqualFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEqualFold(FieldWebdavUsername, v))
}

// WebdavUsernameContainsFold applies the ContainsFold predicate on the "webdav_username" field.
func WebdavUsernameContainsFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContainsFold(FieldWebdavUsername, v))
}

// WebdavPasswordHashEQ applies the EQ predicate on the "webdav_password_hash" field.
func WebdavPasswordHashEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashNEQ applies the NEQ predicate on the "webdav_password_hash" field.
func WebdavPasswordHashNEQ(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashIn applies the In predicate on the "webdav_password_hash" field.
func WebdavPasswordHashIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldWebdavPasswordHash, vs...))
}

// WebdavPasswordHashNotIn applies the NotIn predicate on the "webdav_password_hash" field.
func WebdavPasswordHashNotIn(vs ...string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldWebdavPasswordHash, vs...))
}

// WebdavPasswordHashGT applies the GT predicate on the "webdav_password_hash" field.
func WebdavPasswordHashGT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashGTE applies the GTE predicate on the "webdav_password_hash" field.
func WebdavPasswordHashGTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashLT applies the LT predicate on the "webdav_password_hash" field.
func WebdavPasswordHashLT(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashLTE applies the LTE predicate on the "webdav_password_hash" field.
func WebdavPasswordHashLTE(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashContains applies the Contains predicate on the "webdav_password_hash" field.
func WebdavPasswordHashContains(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContains(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashHasPrefix applies the HasPrefix predicate on the "webdav_password_hash" field.
func WebdavPasswordHashHasPrefix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasPrefix(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashHasSuffix applies the HasSuffix predicate on the "webdav_password_hash" field.
func WebdavPasswordHashHasSuffix(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldHasSuffix(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashEqualFold applies the EqualFold predicate on the "webdav_password_hash" field.
func WebdavPasswordHashEqualFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEqualFold(FieldWebdavPasswordHash, v))
}

// WebdavPasswordHashContainsFold applies the ContainsFold predicate on the "webdav_password_hash" field.
func WebdavPasswordHashContainsFold(v string) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldContainsFold(FieldWebdavPasswordHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.R2WebDAVSetting) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.R2WebDAVSetting) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.R2WebDAVSetting) predicate.R2WebDAVSetting {
	return predicate.R2WebDAVSetting(sql.NotPredicates(p))
}
