// Code generated by ent, DO NOT EDIT.

package oauthvalidationreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthvalidationreport type in the database.
	Label = "oauth_validation_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReportID holds the string denoting the report_id field in the database.
	FieldReportID = "report_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldSessionLabel holds the string denoting the session_label field in the database.
	FieldSessionLabel = "session_label"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountName holds the string denoting the account_name field in the database.
	FieldAccountName = "account_name"
	// FieldZoneID holds the string denoting the zone_id field in the database.
	FieldZoneID = "zone_id"
	// FieldZoneName holds the string denoting the zone_name field in the database.
	FieldZoneName = "zone_name"
	// FieldGeneratedAt holds the string denoting the generated_at field in the database.
	FieldGeneratedAt = "generated_at"
	// FieldSavedAt holds the string denoting the saved_at field in the database.
	FieldSavedAt = "saved_at"
	// FieldScopeMissing holds the string denoting the scope_missing field in the database.
	FieldScopeMissing = "scope_missing"
	// FieldAPIUnavailable holds the string denoting the api_unavailable field in the database.
	FieldAPIUnavailable = "api_unavailable"
	// FieldAPIMissingScope holds the string denoting the api_missing_scope field in the database.
	FieldAPIMissingScope = "api_missing_scope"
	// FieldActionItems holds the string denoting the action_items field in the database.
	FieldActionItems = "action_items"
	// FieldReportBody holds the string denoting the report_body field in the database.
	FieldReportBody = "report_body"
	// Table holds the table name of the oauthvalidationreport in the database.
	Table = "oauth_validation_reports"
)

// Columns holds all SQL columns for oauthvalidationreport fields.
var Columns = []string{
	FieldID,
	FieldReportID,
	FieldSessionID,
	FieldSessionLabel,
	FieldAccountID,
	FieldAccountName,
	FieldZoneID,
	FieldZoneName,
	FieldGeneratedAt,
	FieldSavedAt,
	FieldScopeMissing,
	FieldAPIUnavailable,
	FieldAPIMissingScope,
	FieldActionItems,
	FieldReportBody,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ReportIDValidator is a validator for the "report_id" field. It is called by the builders before save.
	ReportIDValidator func(string) error
	// DefaultSessionID holds the default value on creation for the "session_id" field.
	DefaultSessionID string
	// DefaultSessionLabel holds the default value on creation for the "session_label" field.
	DefaultSessionLabel string
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultAccountName holds the default value on creation for the "account_name" field.
	DefaultAccountName string
	// DefaultZoneID holds the default value on creation for the "zone_id" field.
	DefaultZoneID string
	// DefaultZoneName holds the default value on creation for the "zone_name" field.
	DefaultZoneName string
	// DefaultSavedAt holds the default value on creation for the "saved_at" field.
	DefaultSavedAt func() time.Time
	// DefaultScopeMissing holds the default value on creation for the "scope_missing" field.
	DefaultScopeMissing int
	// DefaultAPIUnavailable holds the default value on creation for the "api_unavailable" field.
	DefaultAPIUnavailable int
	// DefaultAPIMissingScope holds the default value on creation for the "api_missing_scope" field.
	DefaultAPIMissingScope int
	// DefaultActionItems holds the default value on creation for the "action_items" field.
	DefaultActionItems int
	// ReportBodyValidator is a validator for the "report_body" field. It is called by the builders before save.
	ReportBodyValidator func(string) error
)

// OrderOption defines the ordering options for the OAuthValidationReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReportID orders the results by the report_id field.
func ByReportID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// BySessionLabel orders the results by the session_label field.
func BySessionLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionLabel, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountName orders the results by the account_name field.
func ByAccountName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountName, opts...).ToFunc()
}

// ByZoneID orders the results by the zone_id field.
func ByZoneID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZoneID, opts...).ToFunc()
}

// ByZoneName orders the results by the zone_name field.
func ByZoneName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZoneName, opts...).ToFunc()
}

// ByGeneratedAt orders the results by the generated_at field.
func ByGeneratedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneratedAt, opts...).ToFunc()
}

// BySavedAt orders the results by the saved_at field.
func BySavedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSavedAt, opts...).ToFunc()
}

// ByScopeMissing orders the results by the scope_missing field.
func ByScopeMissing(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeMissing, opts...).ToFunc()
}

// ByAPIUnavailable orders the results by the api_unavailable field.
func ByAPIUnavailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIUnavailable, opts...).ToFunc()
}

// ByAPIMissingScope orders the results by the api_missing_scope field.
func ByAPIMissingScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIMissingScope, opts...).ToFunc()
}

// ByActionItems orders the results by the action_items field.
func ByActionItems(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionItems, opts...).ToFunc()
}

// ByReportBody orders the results by the report_body field.
func ByReportBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportBody, opts...).ToFunc()
}
