// Code generated by ent, DO NOT EDIT.

package oauthvalidationreport

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldID, id))
}

// ReportID applies equality check predicate on the "report_id" field. It's identical to ReportIDEQ.
func ReportID(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldReportID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldSessionID, v))
}

// SessionLabel applies equality check predicate on the "session_label" field. It's identical to SessionLabelEQ.
func SessionLabel(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldSessionLabel, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAccountID, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAccountName, v))
}

// ZoneID applies equality check predicate on the "zone_id" field. It's identical to ZoneIDEQ.
func ZoneID(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldZoneID, v))
}

// ZoneName applies equality check predicate on the "zone_name" field. It's identical to ZoneNameEQ.
func ZoneName(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldZoneName, v))
}

// GeneratedAt applies equality check predicate on the "generated_at" field. It's identical to GeneratedAtEQ.
func GeneratedAt(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldGeneratedAt, v))
}

// SavedAt applies equality check predicate on the "saved_at" field. It's identical to SavedAtEQ.
func SavedAt(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldSavedAt, v))
}

// ScopeMissing applies equality check predicate on the "scope_missing" field. It's identical to ScopeMissingEQ.
func ScopeMissing(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldScopeMissing, v))
}

// APIUnavailable applies equality check predicate on the "api_unavailable" field. It's identical to APIUnavailableEQ.
func APIUnavailable(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAPIUnavailable, v))
}

// APIMissingScope applies equality check predicate on the "api_missing_scope" field. It's identical to APIMissingScopeEQ.
func APIMissingScope(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAPIMissingScope, v))
}

// ActionItems applies equality check predicate on the "action_items" field. It's identical to ActionItemsEQ.
func ActionItems(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldActionItems, v))
}

// ReportBody applies equality check predicate on the "report_body" field. It's identical to ReportBodyEQ.
func ReportBody(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldReportBody, v))
}

// ReportIDEQ applies the EQ predicate on the "report_id" field.
func ReportIDEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldReportID, v))
}

// ReportIDNEQ applies the NEQ predicate on the "report_id" field.
func ReportIDNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldReportID, v))
}

// ReportIDIn applies the In predicate on the "report_id" field.
func ReportIDIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldReportID, vs...))
}

// ReportIDNotIn applies the NotIn predicate on the "report_id" field.
func ReportIDNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldReportID, vs...))
}

// ReportIDGT applies the GT predicate on the "report_id" field.
func ReportIDGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldReportID, v))
}

// ReportIDGTE applies the GTE predicate on the "report_id" field.
func ReportIDGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldReportID, v))
}

// ReportIDLT applies the LT predicate on the "report_id" field.
func ReportIDLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldReportID, v))
}

// ReportIDLTE applies the LTE predicate on the "report_id" field.
func ReportIDLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldReportID, v))
}

// ReportIDContains applies the Contains predicate on the "report_id" field.
func ReportIDContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldReportID, v))
}

// ReportIDHasPrefix applies the HasPrefix predicate on the "report_id" field.
func ReportIDHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldReportID, v))
}

// ReportIDHasSuffix applies the HasSuffix predicate on the "report_id" field.
func ReportIDHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldReportID, v))
}

// ReportIDEqualFold applies the EqualFold predicate on the "report_id" field.
func ReportIDEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldReportID, v))
}

// ReportIDContainsFold applies the ContainsFold predicate on the "report_id" field.
func ReportIDContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldReportID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldSessionID, v))
}

// SessionLabelEQ applies the EQ predicate on the "session_label" field.
func SessionLabelEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldSessionLabel, v))
}

// SessionLabelNEQ applies the NEQ predicate on the "session_label" field.
func SessionLabelNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldSessionLabel, v))
}

// SessionLabelIn applies the In predicate on the "session_label" field.
func SessionLabelIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldSessionLabel, vs...))
}

// SessionLabelNotIn applies the NotIn predicate on the "session_label" field.
func SessionLabelNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldSessionLabel, vs...))
}

// SessionLabelGT applies the GT predicate on the "session_label" field.
func SessionLabelGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldSessionLabel, v))
}

// SessionLabelGTE applies the GTE predicate on the "session_label" field.
func SessionLabelGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldSessionLabel, v))
}

// SessionLabelLT applies the LT predicate on the "session_label" field.
func SessionLabelLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldSessionLabel, v))
}

// SessionLabelLTE applies the LTE predicate on the "session_label" field.
func SessionLabelLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldSessionLabel, v))
}

// SessionLabelContains applies the Contains predicate on the "session_label" field.
func SessionLabelContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldSessionLabel, v))
}

// SessionLabelHasPrefix applies the HasPrefix predicate on the "session_label" field.
func SessionLabelHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldSessionLabel, v))
}

// SessionLabelHasSuffix applies the HasSuffix predicate on the "session_label" field.
func SessionLabelHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldSessionLabel, v))
}

// SessionLabelEqualFold applies the EqualFold predicate on the "session_label" field.
func SessionLabelEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldSessionLabel, v))
}

// SessionLabelContainsFold applies the ContainsFold predicate on the "session_label" field.
func SessionLabelContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldSessionLabel, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldAccountID, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldAccountName, v))
}

// ZoneIDEQ applies the EQ predicate on the "zone_id" field.
func ZoneIDEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldZoneID, v))
}

// ZoneIDNEQ applies the NEQ predicate on the "zone_id" field.
func ZoneIDNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldZoneID, v))
}

// ZoneIDIn applies the In predicate on the "zone_id" field.
func ZoneIDIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldZoneID, vs...))
}

// ZoneIDNotIn applies the NotIn predicate on the "zone_id" field.
func ZoneIDNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldZoneID, vs...))
}

// ZoneIDGT applies the GT predicate on the "zone_id" field.
func ZoneIDGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldZoneID, v))
}

// ZoneIDGTE applies the GTE predicate on the "zone_id" field.
func ZoneIDGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldZoneID, v))
}

// ZoneIDLT applies the LT predicate on the "zone_id" field.
func ZoneIDLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldZoneID, v))
}

// ZoneIDLTE applies the LTE predicate on the "zone_id" field.
func ZoneIDLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldZoneID, v))
}

// ZoneIDContains applies the Contains predicate on the "zone_id" field.
func ZoneIDContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldZoneID, v))
}

// ZoneIDHasPrefix applies the HasPrefix predicate on the "zone_id" field.
func ZoneIDHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldZoneID, v))
}

// ZoneIDHasSuffix applies the HasSuffix predicate on the "zone_id" field.
func ZoneIDHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldZoneID, v))
}

// ZoneIDEqualFold applies the EqualFold predicate on the "zone_id" field.
func ZoneIDEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldZoneID, v))
}

// ZoneIDContainsFold applies the ContainsFold predicate on the "zone_id" field.
func ZoneIDContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldZoneID, v))
}

// ZoneNameEQ applies the EQ predicate on the "zone_name" field.
func ZoneNameEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldZoneName, v))
}

// ZoneNameNEQ applies the NEQ predicate on the "zone_name" field.
func ZoneNameNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldZoneName, v))
}

// ZoneNameIn applies the In predicate on the "zone_name" field.
func ZoneNameIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldZoneName, vs...))
}

// ZoneNameNotIn applies the NotIn predicate on the "zone_name" field.
func ZoneNameNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldZoneName, vs...))
}

// ZoneNameGT applies the GT predicate on the "zone_name" field.
func ZoneNameGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldZoneName, v))
}

// ZoneNameGTE applies the GTE predicate on the "zone_name" field.
func ZoneNameGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldZoneName, v))
}

// ZoneNameLT applies the LT predicate on the "zone_name" field.
func ZoneNameLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldZoneName, v))
}

// ZoneNameLTE applies the LTE predicate on the "zone_name" field.
func ZoneNameLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldZoneName, v))
}

// ZoneNameContains applies the Contains predicate on the "zone_name" field.
func ZoneNameContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldZoneName, v))
}

// ZoneNameHasPrefix applies the HasPrefix predicate on the "zone_name" field.
func ZoneNameHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldZoneName, v))
}

// ZoneNameHasSuffix applies the HasSuffix predicate on the "zone_name" field.
func ZoneNameHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldZoneName, v))
}

// ZoneNameEqualFold applies the EqualFold predicate on the "zone_name" field.
func ZoneNameEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldZoneName, v))
}

// ZoneNameContainsFold applies the ContainsFold predicate on the "zone_name" field.
func ZoneNameContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldZoneName, v))
}

// GeneratedAtEQ applies the EQ predicate on the "generated_at" field.
func GeneratedAtEQ(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldGeneratedAt, v))
}

// GeneratedAtNEQ applies the NEQ predicate on the "generated_at" field.
func GeneratedAtNEQ(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldGeneratedAt, v))
}

// GeneratedAtIn applies the In predicate on the "generated_at" field.
func GeneratedAtIn(vs ...time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldGeneratedAt, vs...))
}

// GeneratedAtNotIn applies the NotIn predicate on the "generated_at" field.
func GeneratedAtNotIn(vs ...time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldGeneratedAt, vs...))
}

// GeneratedAtGT applies the GT predicate on the "generated_at" field.
func GeneratedAtGT(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldGeneratedAt, v))
}

// GeneratedAtGTE applies the GTE predicate on the "generated_at" field.
func GeneratedAtGTE(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldGeneratedAt, v))
}

// GeneratedAtLT applies the LT predicate on the "generated_at" field.
func GeneratedAtLT(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldGeneratedAt, v))
}

// GeneratedAtLTE applies the LTE predicate on the "generated_at" field.
func GeneratedAtLTE(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldGeneratedAt, v))
}

// SavedAtEQ applies the EQ predicate on the "saved_at" field.
func SavedAtEQ(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldSavedAt, v))
}

// SavedAtNEQ applies the NEQ predicate on the "saved_at" field.
func SavedAtNEQ(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldSavedAt, v))
}

// SavedAtIn applies the In predicate on the "saved_at" field.
func SavedAtIn(vs ...time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldSavedAt, vs...))
}

// SavedAtNotIn applies the NotIn predicate on the "saved_at" field.
func SavedAtNotIn(vs ...time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldSavedAt, vs...))
}

// SavedAtGT applies the GT predicate on the "saved_at" field.
func SavedAtGT(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldSavedAt, v))
}

// SavedAtGTE applies the GTE predicate on the "saved_at" field.
func SavedAtGTE(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldSavedAt, v))
}

// SavedAtLT applies the LT predicate on the "saved_at" field.
func SavedAtLT(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldSavedAt, v))
}

// SavedAtLTE applies the LTE predicate on the "saved_at" field.
func SavedAtLTE(v time.Time) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldSavedAt, v))
}

// ScopeMissingEQ applies the EQ predicate on the "scope_missing" field.
func ScopeMissingEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldScopeMissing, v))
}

// ScopeMissingNEQ applies the NEQ predicate on the "scope_missing" field.
func ScopeMissingNEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldScopeMissing, v))
}

// ScopeMissingIn applies the In predicate on the "scope_missing" field.
func ScopeMissingIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldScopeMissing, vs...))
}

// ScopeMissingNotIn applies the NotIn predicate on the "scope_missing" field.
func ScopeMissingNotIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldScopeMissing, vs...))
}

// ScopeMissingGT applies the GT predicate on the "scope_missing" field.
func ScopeMissingGT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldScopeMissing, v))
}

// ScopeMissingGTE applies the GTE predicate on the "scope_missing" field.
func ScopeMissingGTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldScopeMissing, v))
}

// ScopeMissingLT applies the LT predicate on the "scope_missing" field.
func ScopeMissingLT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldScopeMissing, v))
}

// ScopeMissingLTE applies the LTE predicate on the "scope_missing" field.
func ScopeMissingLTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldScopeMissing, v))
}

// APIUnavailableEQ applies the EQ predicate on the "api_unavailable" field.
func APIUnavailableEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAPIUnavailable, v))
}

// APIUnavailableNEQ applies the NEQ predicate on the "api_unavailable" field.
func APIUnavailableNEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldAPIUnavailable, v))
}

// APIUnavailableIn applies the In predicate on the "api_unavailable" field.
func APIUnavailableIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldAPIUnavailable, vs...))
}

// APIUnavailableNotIn applies the NotIn predicate on the "api_unavailable" field.
func APIUnavailableNotIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldAPIUnavailable, vs...))
}

// APIUnavailableGT applies the GT predicate on the "api_unavailable" field.
func APIUnavailableGT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldAPIUnavailable, v))
}

// APIUnavailableGTE applies the GTE predicate on the "api_unavailable" field.
func APIUnavailableGTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldAPIUnavailable, v))
}

// APIUnavailableLT applies the LT predicate on the "api_unavailable" field.
func APIUnavailableLT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldAPIUnavailable, v))
}

// APIUnavailableLTE applies the LTE predicate on the "api_unavailable" field.
func APIUnavailableLTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldAPIUnavailable, v))
}

// APIMissingScopeEQ applies the EQ predicate on the "api_missing_scope" field.
func APIMissingScopeEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldAPIMissingScope, v))
}

// APIMissingScopeNEQ applies the NEQ predicate on the "api_missing_scope" field.
func APIMissingScopeNEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldAPIMissingScope, v))
}

// APIMissingScopeIn applies the In predicate on the "api_missing_scope" field.
func APIMissingScopeIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldAPIMissingScope, vs...))
}

// APIMissingScopeNotIn applies the NotIn predicate on the "api_missing_scope" field.
func APIMissingScopeNotIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldAPIMissingScope, vs...))
}

// APIMissingScopeGT applies the GT predicate on the "api_missing_scope" field.
func APIMissingScopeGT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldAPIMissingScope, v))
}

// APIMissingScopeGTE applies the GTE predicate on the "api_missing_scope" field.
func APIMissingScopeGTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldAPIMissingScope, v))
}

// APIMissingScopeLT applies the LT predicate on the "api_missing_scope" field.
func APIMissingScopeLT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldAPIMissingScope, v))
}

// APIMissingScopeLTE applies the LTE predicate on the "api_missing_scope" field.
func APIMissingScopeLTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldAPIMissingScope, v))
}

// ActionItemsEQ applies the EQ predicate on the "action_items" field.
func ActionItemsEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldActionItems, v))
}

// ActionItemsNEQ applies the NEQ predicate on the "action_items" field.
func ActionItemsNEQ(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldActionItems, v))
}

// ActionItemsIn applies the In predicate on the "action_items" field.
func ActionItemsIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldActionItems, vs...))
}

// ActionItemsNotIn applies the NotIn predicate on the "action_items" field.
func ActionItemsNotIn(vs ...int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldActionItems, vs...))
}

// ActionItemsGT applies the GT predicate on the "action_items" field.
func ActionItemsGT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldActionItems, v))
}

// ActionItemsGTE applies the GTE predicate on the "action_items" field.
func ActionItemsGTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldActionItems, v))
}

// ActionItemsLT applies the LT predicate on the "action_items" field.
func ActionItemsLT(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldActionItems, v))
}

// ActionItemsLTE applies the LTE predicate on the "action_items" field.
func ActionItemsLTE(v int) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldActionItems, v))
}

// ReportBodyEQ applies the EQ predicate on the "report_body" field.
func ReportBodyEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEQ(FieldReportBody, v))
}

// ReportBodyNEQ applies the NEQ predicate on the "report_body" field.
func ReportBodyNEQ(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNEQ(FieldReportBody, v))
}

// ReportBodyIn applies the In predicate on the "report_body" field.
func ReportBodyIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldIn(FieldReportBody, vs...))
}

// ReportBodyNotIn applies the NotIn predicate on the "report_body" field.
func ReportBodyNotIn(vs ...string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldNotIn(FieldReportBody, vs...))
}

// ReportBodyGT applies the GT predicate on the "report_body" field.
func ReportBodyGT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGT(FieldReportBody, v))
}

// ReportBodyGTE applies the GTE predicate on the "report_body" field.
func ReportBodyGTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldGTE(FieldReportBody, v))
}

// ReportBodyLT applies the LT predicate on the "report_body" field.
func ReportBodyLT(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLT(FieldReportBody, v))
}

// ReportBodyLTE applies the LTE predicate on the "report_body" field.
func ReportBodyLTE(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldLTE(FieldReportBody, v))
}

// ReportBodyContains applies the Contains predicate on the "report_body" field.
func ReportBodyContains(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContains(FieldReportBody, v))
}

// ReportBodyHasPrefix applies the HasPrefix predicate on the "report_body" field.
func ReportBodyHasPrefix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasPrefix(FieldReportBody, v))
}

// ReportBodyHasSuffix applies the HasSuffix predicate on the "report_body" field.
func ReportBodyHasSuffix(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldHasSuffix(FieldReportBody, v))
}

// ReportBodyEqualFold applies the EqualFold predicate on the "report_body" field.
func ReportBodyEqualFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldEqualFold(FieldReportBody, v))
}

// ReportBodyContainsFold applies the ContainsFold predicate on the "report_body" field.
func ReportBodyContainsFold(v string) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.FieldContainsFold(FieldReportBody, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthValidationReport) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthValidationReport) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthValidationReport) predicate.OAuthValidationReport {
	return predicate.OAuthValidationReport(sql.NotPredicates(p))
}
