// Code generated by ent, DO NOT EDIT.

package tunnelmanagement

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tunnelmanagement type in the database.
	Label = "tunnel_management"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTunnelID holds the string denoting the tunnel_id field in the database.
	FieldTunnelID = "tunnel_id"
	// FieldAPIToken holds the string denoting the api_token field in the database.
	FieldAPIToken = "api_token"
	// FieldAPIEmail holds the string denoting the api_email field in the database.
	FieldAPIEmail = "api_email"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the tunnelmanagement in the database.
	Table = "tunnel_managements"
)

// Columns holds all SQL columns for tunnelmanagement fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldEnabled,
	FieldAccountID,
	FieldTunnelID,
	FieldAPIToken,
	FieldAPIEmail,
	FieldAPIKey,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultTunnelID holds the default value on creation for the "tunnel_id" field.
	DefaultTunnelID string
	// DefaultAPIToken holds the default value on creation for the "api_token" field.
	DefaultAPIToken string
	// DefaultAPIEmail holds the default value on creation for the "api_email" field.
	DefaultAPIEmail string
	// DefaultAPIKey holds the default value on creation for the "api_key" field.
	DefaultAPIKey string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the TunnelManagement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTunnelID orders the results by the tunnel_id field.
func ByTunnelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTunnelID, opts...).ToFunc()
}

// ByAPIToken orders the results by the api_token field.
func ByAPIToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIToken, opts...).ToFunc()
}

// ByAPIEmail orders the results by the api_email field.
func ByAPIEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIEmail, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
