// Code generated by ent, DO NOT EDIT.

package tunnelmanagement

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldKey, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldEnabled, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAccountID, v))
}

// TunnelID applies equality check predicate on the "tunnel_id" field. It's identical to TunnelIDEQ.
func TunnelID(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldTunnelID, v))
}

// APIToken applies equality check predicate on the "api_token" field. It's identical to APITokenEQ.
func APIToken(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAPIToken, v))
}

// APIEmail applies equality check predicate on the "api_email" field. It's identical to APIEmailEQ.
func APIEmail(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAPIEmail, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAPIKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContainsFold(FieldKey, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldEnabled, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContainsFold(FieldAccountID, v))
}

// TunnelIDEQ applies the EQ predicate on the "tunnel_id" field.
func TunnelIDEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldTunnelID, v))
}

// TunnelIDNEQ applies the NEQ predicate on the "tunnel_id" field.
func TunnelIDNEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldTunnelID, v))
}

// TunnelIDIn applies the In predicate on the "tunnel_id" field.
func TunnelIDIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldTunnelID, vs...))
}

// TunnelIDNotIn applies the NotIn predicate on the "tunnel_id" field.
func TunnelIDNotIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldTunnelID, vs...))
}

// TunnelIDGT applies the GT predicate on the "tunnel_id" field.
func TunnelIDGT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldTunnelID, v))
}

// TunnelIDGTE applies the GTE predicate on the "tunnel_id" field.
func TunnelIDGTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldTunnelID, v))
}

// TunnelIDLT applies the LT predicate on the "tunnel_id" field.
func TunnelIDLT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldTunnelID, v))
}

// TunnelIDLTE applies the LTE predicate on the "tunnel_id" field.
func TunnelIDLTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldTunnelID, v))
}

// TunnelIDContains applies the Contains predicate on the "tunnel_id" field.
func TunnelIDContains(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContains(FieldTunnelID, v))
}

// TunnelIDHasPrefix applies the HasPrefix predicate on the "tunnel_id" field.
func TunnelIDHasPrefix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasPrefix(FieldTunnelID, v))
}

// TunnelIDHasSuffix applies the HasSuffix predicate on the "tunnel_id" field.
func TunnelIDHasSuffix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasSuffix(FieldTunnelID, v))
}

// TunnelIDEqualFold applies the EqualFold predicate on the "tunnel_id" field.
func TunnelIDEqualFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEqualFold(FieldTunnelID, v))
}

// TunnelIDContainsFold applies the ContainsFold predicate on the "tunnel_id" field.
func TunnelIDContainsFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContainsFold(FieldTunnelID, v))
}

// APITokenEQ applies the EQ predicate on the "api_token" field.
func APITokenEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAPIToken, v))
}

// APITokenNEQ applies the NEQ predicate on the "api_token" field.
func APITokenNEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldAPIToken, v))
}

// APITokenIn applies the In predicate on the "api_token" field.
func APITokenIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldAPIToken, vs...))
}

// APITokenNotIn applies the NotIn predicate on the "api_token" field.
func APITokenNotIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldAPIToken, vs...))
}

// APITokenGT applies the GT predicate on the "api_token" field.
func APITokenGT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldAPIToken, v))
}

// APITokenGTE applies the GTE predicate on the "api_token" field.
func APITokenGTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldAPIToken, v))
}

// APITokenLT applies the LT predicate on the "api_token" field.
func APITokenLT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldAPIToken, v))
}

// APITokenLTE applies the LTE predicate on the "api_token" field.
func APITokenLTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldAPIToken, v))
}

// APITokenContains applies the Contains predicate on the "api_token" field.
func APITokenContains(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContains(FieldAPIToken, v))
}

// APITokenHasPrefix applies the HasPrefix predicate on the "api_token" field.
func APITokenHasPrefix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasPrefix(FieldAPIToken, v))
}

// APITokenHasSuffix applies the HasSuffix predicate on the "api_token" field.
func APITokenHasSuffix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasSuffix(FieldAPIToken, v))
}

// APITokenEqualFold applies the EqualFold predicate on the "api_token" field.
func APITokenEqualFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEqualFold(FieldAPIToken, v))
}

// APITokenContainsFold applies the ContainsFold predicate on the "api_token" field.
func APITokenContainsFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContainsFold(FieldAPIToken, v))
}

// APIEmailEQ applies the EQ predicate on the "api_email" field.
func APIEmailEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAPIEmail, v))
}

// APIEmailNEQ applies the NEQ predicate on the "api_email" field.
func APIEmailNEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldAPIEmail, v))
}

// APIEmailIn applies the In predicate on the "api_email" field.
func APIEmailIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldAPIEmail, vs...))
}

// APIEmailNotIn applies the NotIn predicate on the "api_email" field.
func APIEmailNotIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldAPIEmail, vs...))
}

// APIEmailGT applies the GT predicate on the "api_email" field.
func APIEmailGT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldAPIEmail, v))
}

// APIEmailGTE applies the GTE predicate on the "api_email" field.
func APIEmailGTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldAPIEmail, v))
}

// APIEmailLT applies the LT predicate on the "api_email" field.
func APIEmailLT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldAPIEmail, v))
}

// APIEmailLTE applies the LTE predicate on the "api_email" field.
func APIEmailLTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldAPIEmail, v))
}

// APIEmailContains applies the Contains predicate on the "api_email" field.
func APIEmailContains(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContains(FieldAPIEmail, v))
}

// APIEmailHasPrefix applies the HasPrefix predicate on the "api_email" field.
func APIEmailHasPrefix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasPrefix(FieldAPIEmail, v))
}

// APIEmailHasSuffix applies the HasSuffix predicate on the "api_email" field.
func APIEmailHasSuffix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasSuffix(FieldAPIEmail, v))
}

// APIEmailEqualFold applies the EqualFold predicate on the "api_email" field.
func APIEmailEqualFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEqualFold(FieldAPIEmail, v))
}

// APIEmailContainsFold applies the ContainsFold predicate on the "api_email" field.
func APIEmailContainsFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContainsFold(FieldAPIEmail, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldContainsFold(FieldAPIKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TunnelManagement) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TunnelManagement) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TunnelManagement) predicate.TunnelManagement {
	return predicate.TunnelManagement(sql.NotPredicates(p))
}
