// Code generated by ent, DO NOT EDIT.

package ddnssetting

import (
	"cfui/internal/persist/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldKey, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldEnabled, v))
}

// IntervalMins applies equality check predicate on the "interval_mins" field. It's identical to IntervalMinsEQ.
func IntervalMins(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldIntervalMins, v))
}

// OnlyOnChange applies equality check predicate on the "only_on_change" field. It's identical to OnlyOnChangeEQ.
func OnlyOnChange(v bool) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldOnlyOnChange, v))
}

// MaxRetries applies equality check predicate on the "max_retries" field. It's identical to MaxRetriesEQ.
func MaxRetries(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldMaxRetries, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldContainsFold(FieldKey, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldEnabled, v))
}

// IntervalMinsEQ applies the EQ predicate on the "interval_mins" field.
func IntervalMinsEQ(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldIntervalMins, v))
}

// IntervalMinsNEQ applies the NEQ predicate on the "interval_mins" field.
func IntervalMinsNEQ(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldIntervalMins, v))
}

// IntervalMinsIn applies the In predicate on the "interval_mins" field.
func IntervalMinsIn(vs ...int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldIn(FieldIntervalMins, vs...))
}

// IntervalMinsNotIn applies the NotIn predicate on the "interval_mins" field.
func IntervalMinsNotIn(vs ...int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNotIn(FieldIntervalMins, vs...))
}

// IntervalMinsGT applies the GT predicate on the "interval_mins" field.
func IntervalMinsGT(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGT(FieldIntervalMins, v))
}

// IntervalMinsGTE applies the GTE predicate on the "interval_mins" field.
func IntervalMinsGTE(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGTE(FieldIntervalMins, v))
}

// IntervalMinsLT applies the LT predicate on the "interval_mins" field.
func IntervalMinsLT(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLT(FieldIntervalMins, v))
}

// IntervalMinsLTE applies the LTE predicate on the "interval_mins" field.
func IntervalMinsLTE(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLTE(FieldIntervalMins, v))
}

// OnlyOnChangeEQ applies the EQ predicate on the "only_on_change" field.
func OnlyOnChangeEQ(v bool) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldOnlyOnChange, v))
}

// OnlyOnChangeNEQ applies the NEQ predicate on the "only_on_change" field.
func OnlyOnChangeNEQ(v bool) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldOnlyOnChange, v))
}

// MaxRetriesEQ applies the EQ predicate on the "max_retries" field.
func MaxRetriesEQ(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldMaxRetries, v))
}

// MaxRetriesNEQ applies the NEQ predicate on the "max_retries" field.
func MaxRetriesNEQ(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldMaxRetries, v))
}

// MaxRetriesIn applies the In predicate on the "max_retries" field.
func MaxRetriesIn(vs ...int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldIn(FieldMaxRetries, vs...))
}

// MaxRetriesNotIn applies the NotIn predicate on the "max_retries" field.
func MaxRetriesNotIn(vs ...int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNotIn(FieldMaxRetries, vs...))
}

// MaxRetriesGT applies the GT predicate on the "max_retries" field.
func MaxRetriesGT(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGT(FieldMaxRetries, v))
}

// MaxRetriesGTE applies the GTE predicate on the "max_retries" field.
func MaxRetriesGTE(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGTE(FieldMaxRetries, v))
}

// MaxRetriesLT applies the LT predicate on the "max_retries" field.
func MaxRetriesLT(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLT(FieldMaxRetries, v))
}

// MaxRetriesLTE applies the LTE predicate on the "max_retries" field.
func MaxRetriesLTE(v int) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLTE(FieldMaxRetries, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DDNSSetting) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DDNSSetting) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DDNSSetting) predicate.DDNSSetting {
	return predicate.DDNSSetting(sql.NotPredicates(p))
}
