// Code generated by ent, DO NOT EDIT.

package ddnsrecord

import (
	"cfui/internal/persist/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldID, id))
}

// SettingsKey applies equality check predicate on the "settings_key" field. It's identical to SettingsKeyEQ.
func SettingsKey(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldSettingsKey, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldSortOrder, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldName, v))
}

// ZoneID applies equality check predicate on the "zone_id" field. It's identical to ZoneIDEQ.
func ZoneID(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldZoneID, v))
}

// ZoneName applies equality check predicate on the "zone_name" field. It's identical to ZoneNameEQ.
func ZoneName(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldZoneName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldValue, v))
}

// Proxied applies equality check predicate on the "proxied" field. It's identical to ProxiedEQ.
func Proxied(v bool) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldProxied, v))
}

// TTL applies equality check predicate on the "ttl" field. It's identical to TTLEQ.
func TTL(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldTTL, v))
}

// SettingsKeyEQ applies the EQ predicate on the "settings_key" field.
func SettingsKeyEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldSettingsKey, v))
}

// SettingsKeyNEQ applies the NEQ predicate on the "settings_key" field.
func SettingsKeyNEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldSettingsKey, v))
}

// SettingsKeyIn applies the In predicate on the "settings_key" field.
func SettingsKeyIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldSettingsKey, vs...))
}

// SettingsKeyNotIn applies the NotIn predicate on the "settings_key" field.
func SettingsKeyNotIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldSettingsKey, vs...))
}

// SettingsKeyGT applies the GT predicate on the "settings_key" field.
func SettingsKeyGT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldSettingsKey, v))
}

// SettingsKeyGTE applies the GTE predicate on the "settings_key" field.
func SettingsKeyGTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldSettingsKey, v))
}

// SettingsKeyLT applies the LT predicate on the "settings_key" field.
func SettingsKeyLT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldSettingsKey, v))
}

// SettingsKeyLTE applies the LTE predicate on the "settings_key" field.
func SettingsKeyLTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldSettingsKey, v))
}

// SettingsKeyContains applies the Contains predicate on the "settings_key" field.
func SettingsKeyContains(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContains(FieldSettingsKey, v))
}

// SettingsKeyHasPrefix applies the HasPrefix predicate on the "settings_key" field.
func SettingsKeyHasPrefix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasPrefix(FieldSettingsKey, v))
}

// SettingsKeyHasSuffix applies the HasSuffix predicate on the "settings_key" field.
func SettingsKeyHasSuffix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasSuffix(FieldSettingsKey, v))
}

// SettingsKeyEqualFold applies the EqualFold predicate on the "settings_key" field.
func SettingsKeyEqualFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEqualFold(FieldSettingsKey, v))
}

// SettingsKeyContainsFold applies the ContainsFold predicate on the "settings_key" field.
func SettingsKeyContainsFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContainsFold(FieldSettingsKey, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldSortOrder, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContainsFold(FieldName, v))
}

// ZoneIDEQ applies the EQ predicate on the "zone_id" field.
func ZoneIDEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldZoneID, v))
}

// ZoneIDNEQ applies the NEQ predicate on the "zone_id" field.
func ZoneIDNEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldZoneID, v))
}

// ZoneIDIn applies the In predicate on the "zone_id" field.
func ZoneIDIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldZoneID, vs...))
}

// ZoneIDNotIn applies the NotIn predicate on the "zone_id" field.
func ZoneIDNotIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldZoneID, vs...))
}

// ZoneIDGT applies the GT predicate on the "zone_id" field.
func ZoneIDGT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldZoneID, v))
}

// ZoneIDGTE applies the GTE predicate on the "zone_id" field.
func ZoneIDGTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldZoneID, v))
}

// ZoneIDLT applies the LT predicate on the "zone_id" field.
func ZoneIDLT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldZoneID, v))
}

// ZoneIDLTE applies the LTE predicate on the "zone_id" field.
func ZoneIDLTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldZoneID, v))
}

// ZoneIDContains applies the Contains predicate on the "zone_id" field.
func ZoneIDContains(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContains(FieldZoneID, v))
}

// ZoneIDHasPrefix applies the HasPrefix predicate on the "zone_id" field.
func ZoneIDHasPrefix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasPrefix(FieldZoneID, v))
}

// ZoneIDHasSuffix applies the HasSuffix predicate on the "zone_id" field.
func ZoneIDHasSuffix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasSuffix(FieldZoneID, v))
}

// ZoneIDEqualFold applies the EqualFold predicate on the "zone_id" field.
func ZoneIDEqualFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEqualFold(FieldZoneID, v))
}

// ZoneIDContainsFold applies the ContainsFold predicate on the "zone_id" field.
func ZoneIDContainsFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContainsFold(FieldZoneID, v))
}

// ZoneNameEQ applies the EQ predicate on the "zone_name" field.
func ZoneNameEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldZoneName, v))
}

// ZoneNameNEQ applies the NEQ predicate on the "zone_name" field.
func ZoneNameNEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldZoneName, v))
}

// ZoneNameIn applies the In predicate on the "zone_name" field.
func ZoneNameIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldZoneName, vs...))
}

// ZoneNameNotIn applies the NotIn predicate on the "zone_name" field.
func ZoneNameNotIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldZoneName, vs...))
}

// ZoneNameGT applies the GT predicate on the "zone_name" field.
func ZoneNameGT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldZoneName, v))
}

// ZoneNameGTE applies the GTE predicate on the "zone_name" field.
func ZoneNameGTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldZoneName, v))
}

// ZoneNameLT applies the LT predicate on the "zone_name" field.
func ZoneNameLT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldZoneName, v))
}

// ZoneNameLTE applies the LTE predicate on the "zone_name" field.
func ZoneNameLTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldZoneName, v))
}

// ZoneNameContains applies the Contains predicate on the "zone_name" field.
func ZoneNameContains(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContains(FieldZoneName, v))
}

// ZoneNameHasPrefix applies the HasPrefix predicate on the "zone_name" field.
func ZoneNameHasPrefix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasPrefix(FieldZoneName, v))
}

// ZoneNameHasSuffix applies the HasSuffix predicate on the "zone_name" field.
func ZoneNameHasSuffix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasSuffix(FieldZoneName, v))
}

// ZoneNameEqualFold applies the EqualFold predicate on the "zone_name" field.
func ZoneNameEqualFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEqualFold(FieldZoneName, v))
}

// ZoneNameContainsFold applies the ContainsFold predicate on the "zone_name" field.
func ZoneNameContainsFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContainsFold(FieldZoneName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContainsFold(FieldType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldContainsFold(FieldValue, v))
}

// ProxiedEQ applies the EQ predicate on the "proxied" field.
func ProxiedEQ(v bool) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldProxied, v))
}

// ProxiedNEQ applies the NEQ predicate on the "proxied" field.
func ProxiedNEQ(v bool) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldProxied, v))
}

// TTLEQ applies the EQ predicate on the "ttl" field.
func TTLEQ(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldEQ(FieldTTL, v))
}

// TTLNEQ applies the NEQ predicate on the "ttl" field.
func TTLNEQ(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNEQ(FieldTTL, v))
}

// TTLIn applies the In predicate on the "ttl" field.
func TTLIn(vs ...int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldIn(FieldTTL, vs...))
}

// TTLNotIn applies the NotIn predicate on the "ttl" field.
func TTLNotIn(vs ...int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldNotIn(FieldTTL, vs...))
}

// TTLGT applies the GT predicate on the "ttl" field.
func TTLGT(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGT(FieldTTL, v))
}

// TTLGTE applies the GTE predicate on the "ttl" field.
func TTLGTE(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldGTE(FieldTTL, v))
}

// TTLLT applies the LT predicate on the "ttl" field.
func TTLLT(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLT(FieldTTL, v))
}

// TTLLTE applies the LTE predicate on the "ttl" field.
func TTLLTE(v int) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.FieldLTE(FieldTTL, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DDNSRecord) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DDNSRecord) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DDNSRecord) predicate.DDNSRecord {
	return predicate.DDNSRecord(sql.NotPredicates(p))
}
