// Code generated by ent, DO NOT EDIT.

package ddnsipsource

import (
	"cfui/internal/persist/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLTE(FieldID, id))
}

// SettingsKey applies equality check predicate on the "settings_key" field. It's identical to SettingsKeyEQ.
func SettingsKey(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldSettingsKey, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldSortOrder, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldURL, v))
}

// IPType applies equality check predicate on the "ip_type" field. It's identical to IPTypeEQ.
func IPType(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldIPType, v))
}

// SettingsKeyEQ applies the EQ predicate on the "settings_key" field.
func SettingsKeyEQ(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldSettingsKey, v))
}

// SettingsKeyNEQ applies the NEQ predicate on the "settings_key" field.
func SettingsKeyNEQ(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNEQ(FieldSettingsKey, v))
}

// SettingsKeyIn applies the In predicate on the "settings_key" field.
func SettingsKeyIn(vs ...string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldIn(FieldSettingsKey, vs...))
}

// SettingsKeyNotIn applies the NotIn predicate on the "settings_key" field.
func SettingsKeyNotIn(vs ...string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNotIn(FieldSettingsKey, vs...))
}

// SettingsKeyGT applies the GT predicate on the "settings_key" field.
func SettingsKeyGT(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGT(FieldSettingsKey, v))
}

// SettingsKeyGTE applies the GTE predicate on the "settings_key" field.
func SettingsKeyGTE(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGTE(FieldSettingsKey, v))
}

// SettingsKeyLT applies the LT predicate on the "settings_key" field.
func SettingsKeyLT(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLT(FieldSettingsKey, v))
}

// SettingsKeyLTE applies the LTE predicate on the "settings_key" field.
func SettingsKeyLTE(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLTE(FieldSettingsKey, v))
}

// SettingsKeyContains applies the Contains predicate on the "settings_key" field.
func SettingsKeyContains(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldContains(FieldSettingsKey, v))
}

// SettingsKeyHasPrefix applies the HasPrefix predicate on the "settings_key" field.
func SettingsKeyHasPrefix(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldHasPrefix(FieldSettingsKey, v))
}

// SettingsKeyHasSuffix applies the HasSuffix predicate on the "settings_key" field.
func SettingsKeyHasSuffix(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldHasSuffix(FieldSettingsKey, v))
}

// SettingsKeyEqualFold applies the EqualFold predicate on the "settings_key" field.
func SettingsKeyEqualFold(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEqualFold(FieldSettingsKey, v))
}

// SettingsKeyContainsFold applies the ContainsFold predicate on the "settings_key" field.
func SettingsKeyContainsFold(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldContainsFold(FieldSettingsKey, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLTE(FieldSortOrder, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldContainsFold(FieldURL, v))
}

// IPTypeEQ applies the EQ predicate on the "ip_type" field.
func IPTypeEQ(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEQ(FieldIPType, v))
}

// IPTypeNEQ applies the NEQ predicate on the "ip_type" field.
func IPTypeNEQ(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNEQ(FieldIPType, v))
}

// IPTypeIn applies the In predicate on the "ip_type" field.
func IPTypeIn(vs ...string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldIn(FieldIPType, vs...))
}

// IPTypeNotIn applies the NotIn predicate on the "ip_type" field.
func IPTypeNotIn(vs ...string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldNotIn(FieldIPType, vs...))
}

// IPTypeGT applies the GT predicate on the "ip_type" field.
func IPTypeGT(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGT(FieldIPType, v))
}

// IPTypeGTE applies the GTE predicate on the "ip_type" field.
func IPTypeGTE(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldGTE(FieldIPType, v))
}

// IPTypeLT applies the LT predicate on the "ip_type" field.
func IPTypeLT(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLT(FieldIPType, v))
}

// IPTypeLTE applies the LTE predicate on the "ip_type" field.
func IPTypeLTE(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldLTE(FieldIPType, v))
}

// IPTypeContains applies the Contains predicate on the "ip_type" field.
func IPTypeContains(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldContains(FieldIPType, v))
}

// IPTypeHasPrefix applies the HasPrefix predicate on the "ip_type" field.
func IPTypeHasPrefix(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldHasPrefix(FieldIPType, v))
}

// IPTypeHasSuffix applies the HasSuffix predicate on the "ip_type" field.
func IPTypeHasSuffix(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldHasSuffix(FieldIPType, v))
}

// IPTypeEqualFold applies the EqualFold predicate on the "ip_type" field.
func IPTypeEqualFold(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldEqualFold(FieldIPType, v))
}

// IPTypeContainsFold applies the ContainsFold predicate on the "ip_type" field.
func IPTypeContainsFold(v string) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.FieldContainsFold(FieldIPType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DDNSIPSource) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DDNSIPSource) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DDNSIPSource) predicate.DDNSIPSource {
	return predicate.DDNSIPSource(sql.NotPredicates(p))
}
