// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnsipsource"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DDNSIPSource is the model entity for the DDNSIPSource schema.
type DDNSIPSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SettingsKey holds the value of the "settings_key" field.
	SettingsKey string `json:"settings_key,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// IPType holds the value of the "ip_type" field.
	IPType       string `json:"ip_type,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DDNSIPSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ddnsipsource.FieldID, ddnsipsource.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case ddnsipsource.FieldSettingsKey, ddnsipsource.FieldURL, ddnsipsource.FieldIPType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DDNSIPSource fields.
func (_m *DDNSIPSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ddnsipsource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ddnsipsource.FieldSettingsKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field settings_key", values[i])
			} else if value.Valid {
				_m.SettingsKey = value.String
			}
		case ddnsipsource.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case ddnsipsource.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case ddnsipsource.FieldIPType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_type", values[i])
			} else if value.Valid {
				_m.IPType = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DDNSIPSource.
// This includes values selected through modifiers, order, etc.
func (_m *DDNSIPSource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DDNSIPSource.
// Note that you need to call DDNSIPSource.Unwrap() before calling this method if this DDNSIPSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DDNSIPSource) Update() *DDNSIPSourceUpdateOne {
	return NewDDNSIPSourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DDNSIPSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DDNSIPSource) Unwrap() *DDNSIPSource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DDNSIPSource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DDNSIPSource) String() string {
	var builder strings.Builder
	builder.WriteString("DDNSIPSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("settings_key=")
	builder.WriteString(_m.SettingsKey)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("ip_type=")
	builder.WriteString(_m.IPType)
	builder.WriteByte(')')
	return builder.String()
}

// DDNSIPSources is a parsable slice of DDNSIPSource.
type DDNSIPSources []*DDNSIPSource
