// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnssetting"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DDNSSetting is the model entity for the DDNSSetting schema.
type DDNSSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// IntervalMins holds the value of the "interval_mins" field.
	IntervalMins int `json:"interval_mins,omitempty"`
	// OnlyOnChange holds the value of the "only_on_change" field.
	OnlyOnChange bool `json:"only_on_change,omitempty"`
	// MaxRetries holds the value of the "max_retries" field.
	MaxRetries int `json:"max_retries,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DDNSSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ddnssetting.FieldEnabled, ddnssetting.FieldOnlyOnChange:
			values[i] = new(sql.NullBool)
		case ddnssetting.FieldID, ddnssetting.FieldIntervalMins, ddnssetting.FieldMaxRetries:
			values[i] = new(sql.NullInt64)
		case ddnssetting.FieldKey:
			values[i] = new(sql.NullString)
		case ddnssetting.FieldCreatedAt, ddnssetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DDNSSetting fields.
func (_m *DDNSSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ddnssetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ddnssetting.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case ddnssetting.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case ddnssetting.FieldIntervalMins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_mins", values[i])
			} else if value.Valid {
				_m.IntervalMins = int(value.Int64)
			}
		case ddnssetting.FieldOnlyOnChange:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field only_on_change", values[i])
			} else if value.Valid {
				_m.OnlyOnChange = value.Bool
			}
		case ddnssetting.FieldMaxRetries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_retries", values[i])
			} else if value.Valid {
				_m.MaxRetries = int(value.Int64)
			}
		case ddnssetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ddnssetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DDNSSetting.
// This includes values selected through modifiers, order, etc.
func (_m *DDNSSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DDNSSetting.
// Note that you need to call DDNSSetting.Unwrap() before calling this method if this DDNSSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DDNSSetting) Update() *DDNSSettingUpdateOne {
	return NewDDNSSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DDNSSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DDNSSetting) Unwrap() *DDNSSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DDNSSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DDNSSetting) String() string {
	var builder strings.Builder
	builder.WriteString("DDNSSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("interval_mins=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalMins))
	builder.WriteString(", ")
	builder.WriteString("only_on_change=")
	builder.WriteString(fmt.Sprintf("%v", _m.OnlyOnChange))
	builder.WriteString(", ")
	builder.WriteString("max_retries=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRetries))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DDNSSettings is a parsable slice of DDNSSetting.
type DDNSSettings []*DDNSSetting
