// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnsrecord"
	"cfui/internal/persist/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DDNSRecordUpdate is the builder for updating DDNSRecord entities.
type DDNSRecordUpdate struct {
	config
	hooks    []Hook
	mutation *DDNSRecordMutation
}

// Where appends a list predicates to the DDNSRecordUpdate builder.
func (_u *DDNSRecordUpdate) Where(ps ...predicate.DDNSRecord) *DDNSRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSettingsKey sets the "settings_key" field.
func (_u *DDNSRecordUpdate) SetSettingsKey(v string) *DDNSRecordUpdate {
	_u.mutation.SetSettingsKey(v)
	return _u
}

// SetNillableSettingsKey sets the "settings_key" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableSettingsKey(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetSettingsKey(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DDNSRecordUpdate) SetSortOrder(v int) *DDNSRecordUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableSortOrder(v *int) *DDNSRecordUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DDNSRecordUpdate) AddSortOrder(v int) *DDNSRecordUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DDNSRecordUpdate) SetName(v string) *DDNSRecordUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableName(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetZoneID sets the "zone_id" field.
func (_u *DDNSRecordUpdate) SetZoneID(v string) *DDNSRecordUpdate {
	_u.mutation.SetZoneID(v)
	return _u
}

// SetNillableZoneID sets the "zone_id" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableZoneID(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetZoneID(*v)
	}
	return _u
}

// SetZoneName sets the "zone_name" field.
func (_u *DDNSRecordUpdate) SetZoneName(v string) *DDNSRecordUpdate {
	_u.mutation.SetZoneName(v)
	return _u
}

// SetNillableZoneName sets the "zone_name" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableZoneName(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetZoneName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DDNSRecordUpdate) SetType(v string) *DDNSRecordUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableType(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *DDNSRecordUpdate) SetValue(v string) *DDNSRecordUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableValue(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *DDNSRecordUpdate) SetComment(v string) *DDNSRecordUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableComment(v *string) *DDNSRecordUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetProxied sets the "proxied" field.
func (_u *DDNSRecordUpdate) SetProxied(v bool) *DDNSRecordUpdate {
	_u.mutation.SetProxied(v)
	return _u
}

// SetNillableProxied sets the "proxied" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableProxied(v *bool) *DDNSRecordUpdate {
	if v != nil {
		_u.SetProxied(*v)
	}
	return _u
}

// SetTTL sets the "ttl" field.
func (_u *DDNSRecordUpdate) SetTTL(v int) *DDNSRecordUpdate {
	_u.mutation.ResetTTL()
	_u.mutation.SetTTL(v)
	return _u
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (_u *DDNSRecordUpdate) SetNillableTTL(v *int) *DDNSRecordUpdate {
	if v != nil {
		_u.SetTTL(*v)
	}
	return _u
}

// AddTTL adds value to the "ttl" field.
func (_u *DDNSRecordUpdate) AddTTL(v int) *DDNSRecordUpdate {
	_u.mutation.AddTTL(v)
	return _u
}

// Mutation returns the DDNSRecordMutation object of the builder.
func (_u *DDNSRecordUpdate) Mutation() *DDNSRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DDNSRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DDNSRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DDNSRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DDNSRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DDNSRecordUpdate) check() error {
	if v, ok := _u.mutation.SettingsKey(); ok {
		if err := ddnsrecord.SettingsKeyValidator(v); err != nil {
			return &ValidationError{Name: "settings_key", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.settings_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := ddnsrecord.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.sort_order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := ddnsrecord.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ZoneID(); ok {
		if err := ddnsrecord.ZoneIDValidator(v); err != nil {
			return &ValidationError{Name: "zone_id", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.zone_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := ddnsrecord.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.type": %w`, err)}
		}
	}
	return nil
}

func (_u *DDNSRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ddnsrecord.Table, ddnsrecord.Columns, sqlgraph.NewFieldSpec(ddnsrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SettingsKey(); ok {
		_spec.SetField(ddnsrecord.FieldSettingsKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(ddnsrecord.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(ddnsrecord.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ddnsrecord.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneID(); ok {
		_spec.SetField(ddnsrecord.FieldZoneID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneName(); ok {
		_spec.SetField(ddnsrecord.FieldZoneName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ddnsrecord.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(ddnsrecord.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(ddnsrecord.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Proxied(); ok {
		_spec.SetField(ddnsrecord.FieldProxied, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TTL(); ok {
		_spec.SetField(ddnsrecord.FieldTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTTL(); ok {
		_spec.AddField(ddnsrecord.FieldTTL, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ddnsrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DDNSRecordUpdateOne is the builder for updating a single DDNSRecord entity.
type DDNSRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DDNSRecordMutation
}

// SetSettingsKey sets the "settings_key" field.
func (_u *DDNSRecordUpdateOne) SetSettingsKey(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetSettingsKey(v)
	return _u
}

// SetNillableSettingsKey sets the "settings_key" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableSettingsKey(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetSettingsKey(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DDNSRecordUpdateOne) SetSortOrder(v int) *DDNSRecordUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableSortOrder(v *int) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DDNSRecordUpdateOne) AddSortOrder(v int) *DDNSRecordUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DDNSRecordUpdateOne) SetName(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableName(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetZoneID sets the "zone_id" field.
func (_u *DDNSRecordUpdateOne) SetZoneID(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetZoneID(v)
	return _u
}

// SetNillableZoneID sets the "zone_id" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableZoneID(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetZoneID(*v)
	}
	return _u
}

// SetZoneName sets the "zone_name" field.
func (_u *DDNSRecordUpdateOne) SetZoneName(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetZoneName(v)
	return _u
}

// SetNillableZoneName sets the "zone_name" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableZoneName(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetZoneName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DDNSRecordUpdateOne) SetType(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableType(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *DDNSRecordUpdateOne) SetValue(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableValue(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *DDNSRecordUpdateOne) SetComment(v string) *DDNSRecordUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableComment(v *string) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetProxied sets the "proxied" field.
func (_u *DDNSRecordUpdateOne) SetProxied(v bool) *DDNSRecordUpdateOne {
	_u.mutation.SetProxied(v)
	return _u
}

// SetNillableProxied sets the "proxied" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableProxied(v *bool) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetProxied(*v)
	}
	return _u
}

// SetTTL sets the "ttl" field.
func (_u *DDNSRecordUpdateOne) SetTTL(v int) *DDNSRecordUpdateOne {
	_u.mutation.ResetTTL()
	_u.mutation.SetTTL(v)
	return _u
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (_u *DDNSRecordUpdateOne) SetNillableTTL(v *int) *DDNSRecordUpdateOne {
	if v != nil {
		_u.SetTTL(*v)
	}
	return _u
}

// AddTTL adds value to the "ttl" field.
func (_u *DDNSRecordUpdateOne) AddTTL(v int) *DDNSRecordUpdateOne {
	_u.mutation.AddTTL(v)
	return _u
}

// Mutation returns the DDNSRecordMutation object of the builder.
func (_u *DDNSRecordUpdateOne) Mutation() *DDNSRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the DDNSRecordUpdate builder.
func (_u *DDNSRecordUpdateOne) Where(ps ...predicate.DDNSRecord) *DDNSRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DDNSRecordUpdateOne) Select(field string, fields ...string) *DDNSRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DDNSRecord entity.
func (_u *DDNSRecordUpdateOne) Save(ctx context.Context) (*DDNSRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DDNSRecordUpdateOne) SaveX(ctx context.Context) *DDNSRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DDNSRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DDNSRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DDNSRecordUpdateOne) check() error {
	if v, ok := _u.mutation.SettingsKey(); ok {
		if err := ddnsrecord.SettingsKeyValidator(v); err != nil {
			return &ValidationError{Name: "settings_key", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.settings_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := ddnsrecord.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.sort_order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := ddnsrecord.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ZoneID(); ok {
		if err := ddnsrecord.ZoneIDValidator(v); err != nil {
			return &ValidationError{Name: "zone_id", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.zone_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := ddnsrecord.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.type": %w`, err)}
		}
	}
	return nil
}

func (_u *DDNSRecordUpdateOne) sqlSave(ctx context.Context) (_node *DDNSRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ddnsrecord.Table, ddnsrecord.Columns, sqlgraph.NewFieldSpec(ddnsrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DDNSRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ddnsrecord.FieldID)
		for _, f := range fields {
			if !ddnsrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ddnsrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SettingsKey(); ok {
		_spec.SetField(ddnsrecord.FieldSettingsKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(ddnsrecord.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(ddnsrecord.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ddnsrecord.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneID(); ok {
		_spec.SetField(ddnsrecord.FieldZoneID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneName(); ok {
		_spec.SetField(ddnsrecord.FieldZoneName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ddnsrecord.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(ddnsrecord.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(ddnsrecord.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Proxied(); ok {
		_spec.SetField(ddnsrecord.FieldProxied, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TTL(); ok {
		_spec.SetField(ddnsrecord.FieldTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTTL(); ok {
		_spec.AddField(ddnsrecord.FieldTTL, field.TypeInt, value)
	}
	_node = &DDNSRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ddnsrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
