// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnsrecord"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DDNSRecordCreate is the builder for creating a DDNSRecord entity.
type DDNSRecordCreate struct {
	config
	mutation *DDNSRecordMutation
	hooks    []Hook
}

// SetSettingsKey sets the "settings_key" field.
func (_c *DDNSRecordCreate) SetSettingsKey(v string) *DDNSRecordCreate {
	_c.mutation.SetSettingsKey(v)
	return _c
}

// SetNillableSettingsKey sets the "settings_key" field if the given value is not nil.
func (_c *DDNSRecordCreate) SetNillableSettingsKey(v *string) *DDNSRecordCreate {
	if v != nil {
		_c.SetSettingsKey(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *DDNSRecordCreate) SetSortOrder(v int) *DDNSRecordCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DDNSRecordCreate) SetName(v string) *DDNSRecordCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetZoneID sets the "zone_id" field.
func (_c *DDNSRecordCreate) SetZoneID(v string) *DDNSRecordCreate {
	_c.mutation.SetZoneID(v)
	return _c
}

// SetZoneName sets the "zone_name" field.
func (_c *DDNSRecordCreate) SetZoneName(v string) *DDNSRecordCreate {
	_c.mutation.SetZoneName(v)
	return _c
}

// SetNillableZoneName sets the "zone_name" field if the given value is not nil.
func (_c *DDNSRecordCreate) SetNillableZoneName(v *string) *DDNSRecordCreate {
	if v != nil {
		_c.SetZoneName(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *DDNSRecordCreate) SetType(v string) *DDNSRecordCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *DDNSRecordCreate) SetValue(v string) *DDNSRecordCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *DDNSRecordCreate) SetNillableValue(v *string) *DDNSRecordCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetComment sets the "comment" field.
func (_c *DDNSRecordCreate) SetComment(v string) *DDNSRecordCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *DDNSRecordCreate) SetNillableComment(v *string) *DDNSRecordCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetProxied sets the "proxied" field.
func (_c *DDNSRecordCreate) SetProxied(v bool) *DDNSRecordCreate {
	_c.mutation.SetProxied(v)
	return _c
}

// SetNillableProxied sets the "proxied" field if the given value is not nil.
func (_c *DDNSRecordCreate) SetNillableProxied(v *bool) *DDNSRecordCreate {
	if v != nil {
		_c.SetProxied(*v)
	}
	return _c
}

// SetTTL sets the "ttl" field.
func (_c *DDNSRecordCreate) SetTTL(v int) *DDNSRecordCreate {
	_c.mutation.SetTTL(v)
	return _c
}

// SetNillableTTL sets the "ttl" field if the given value is not nil.
func (_c *DDNSRecordCreate) SetNillableTTL(v *int) *DDNSRecordCreate {
	if v != nil {
		_c.SetTTL(*v)
	}
	return _c
}

// Mutation returns the DDNSRecordMutation object of the builder.
func (_c *DDNSRecordCreate) Mutation() *DDNSRecordMutation {
	return _c.mutation
}

// Save creates the DDNSRecord in the database.
func (_c *DDNSRecordCreate) Save(ctx context.Context) (*DDNSRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DDNSRecordCreate) SaveX(ctx context.Context) *DDNSRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DDNSRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DDNSRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DDNSRecordCreate) defaults() {
	if _, ok := _c.mutation.SettingsKey(); !ok {
		v := ddnsrecord.DefaultSettingsKey
		_c.mutation.SetSettingsKey(v)
	}
	if _, ok := _c.mutation.ZoneName(); !ok {
		v := ddnsrecord.DefaultZoneName
		_c.mutation.SetZoneName(v)
	}
	if _, ok := _c.mutation.Value(); !ok {
		v := ddnsrecord.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Comment(); !ok {
		v := ddnsrecord.DefaultComment
		_c.mutation.SetComment(v)
	}
	if _, ok := _c.mutation.Proxied(); !ok {
		v := ddnsrecord.DefaultProxied
		_c.mutation.SetProxied(v)
	}
	if _, ok := _c.mutation.TTL(); !ok {
		v := ddnsrecord.DefaultTTL
		_c.mutation.SetTTL(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DDNSRecordCreate) check() error {
	if _, ok := _c.mutation.SettingsKey(); !ok {
		return &ValidationError{Name: "settings_key", err: errors.New(`ent: missing required field "DDNSRecord.settings_key"`)}
	}
	if v, ok := _c.mutation.SettingsKey(); ok {
		if err := ddnsrecord.SettingsKeyValidator(v); err != nil {
			return &ValidationError{Name: "settings_key", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.settings_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "DDNSRecord.sort_order"`)}
	}
	if v, ok := _c.mutation.SortOrder(); ok {
		if err := ddnsrecord.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.sort_order": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DDNSRecord.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ddnsrecord.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ZoneID(); !ok {
		return &ValidationError{Name: "zone_id", err: errors.New(`ent: missing required field "DDNSRecord.zone_id"`)}
	}
	if v, ok := _c.mutation.ZoneID(); ok {
		if err := ddnsrecord.ZoneIDValidator(v); err != nil {
			return &ValidationError{Name: "zone_id", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.zone_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ZoneName(); !ok {
		return &ValidationError{Name: "zone_name", err: errors.New(`ent: missing required field "DDNSRecord.zone_name"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "DDNSRecord.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := ddnsrecord.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "DDNSRecord.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "DDNSRecord.value"`)}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "DDNSRecord.comment"`)}
	}
	if _, ok := _c.mutation.Proxied(); !ok {
		return &ValidationError{Name: "proxied", err: errors.New(`ent: missing required field "DDNSRecord.proxied"`)}
	}
	if _, ok := _c.mutation.TTL(); !ok {
		return &ValidationError{Name: "ttl", err: errors.New(`ent: missing required field "DDNSRecord.ttl"`)}
	}
	return nil
}

func (_c *DDNSRecordCreate) sqlSave(ctx context.Context) (*DDNSRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DDNSRecordCreate) createSpec() (*DDNSRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &DDNSRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ddnsrecord.Table, sqlgraph.NewFieldSpec(ddnsrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SettingsKey(); ok {
		_spec.SetField(ddnsrecord.FieldSettingsKey, field.TypeString, value)
		_node.SettingsKey = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(ddnsrecord.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ddnsrecord.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ZoneID(); ok {
		_spec.SetField(ddnsrecord.FieldZoneID, field.TypeString, value)
		_node.ZoneID = value
	}
	if value, ok := _c.mutation.ZoneName(); ok {
		_spec.SetField(ddnsrecord.FieldZoneName, field.TypeString, value)
		_node.ZoneName = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(ddnsrecord.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(ddnsrecord.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(ddnsrecord.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Proxied(); ok {
		_spec.SetField(ddnsrecord.FieldProxied, field.TypeBool, value)
		_node.Proxied = value
	}
	if value, ok := _c.mutation.TTL(); ok {
		_spec.SetField(ddnsrecord.FieldTTL, field.TypeInt, value)
		_node.TTL = value
	}
	return _node, _spec
}

// DDNSRecordCreateBulk is the builder for creating many DDNSRecord entities in bulk.
type DDNSRecordCreateBulk struct {
	config
	err      error
	builders []*DDNSRecordCreate
}

// Save creates the DDNSRecord entities in the database.
func (_c *DDNSRecordCreateBulk) Save(ctx context.Context) ([]*DDNSRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DDNSRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DDNSRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DDNSRecordCreateBulk) SaveX(ctx context.Context) []*DDNSRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DDNSRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DDNSRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
