// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnsipsource"
	"cfui/internal/persist/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DDNSIPSourceUpdate is the builder for updating DDNSIPSource entities.
type DDNSIPSourceUpdate struct {
	config
	hooks    []Hook
	mutation *DDNSIPSourceMutation
}

// Where appends a list predicates to the DDNSIPSourceUpdate builder.
func (_u *DDNSIPSourceUpdate) Where(ps ...predicate.DDNSIPSource) *DDNSIPSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSettingsKey sets the "settings_key" field.
func (_u *DDNSIPSourceUpdate) SetSettingsKey(v string) *DDNSIPSourceUpdate {
	_u.mutation.SetSettingsKey(v)
	return _u
}

// SetNillableSettingsKey sets the "settings_key" field if the given value is not nil.
func (_u *DDNSIPSourceUpdate) SetNillableSettingsKey(v *string) *DDNSIPSourceUpdate {
	if v != nil {
		_u.SetSettingsKey(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DDNSIPSourceUpdate) SetSortOrder(v int) *DDNSIPSourceUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DDNSIPSourceUpdate) SetNillableSortOrder(v *int) *DDNSIPSourceUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DDNSIPSourceUpdate) AddSortOrder(v int) *DDNSIPSourceUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *DDNSIPSourceUpdate) SetURL(v string) *DDNSIPSourceUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *DDNSIPSourceUpdate) SetNillableURL(v *string) *DDNSIPSourceUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetIPType sets the "ip_type" field.
func (_u *DDNSIPSourceUpdate) SetIPType(v string) *DDNSIPSourceUpdate {
	_u.mutation.SetIPType(v)
	return _u
}

// SetNillableIPType sets the "ip_type" field if the given value is not nil.
func (_u *DDNSIPSourceUpdate) SetNillableIPType(v *string) *DDNSIPSourceUpdate {
	if v != nil {
		_u.SetIPType(*v)
	}
	return _u
}

// Mutation returns the DDNSIPSourceMutation object of the builder.
func (_u *DDNSIPSourceUpdate) Mutation() *DDNSIPSourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DDNSIPSourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DDNSIPSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DDNSIPSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DDNSIPSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DDNSIPSourceUpdate) check() error {
	if v, ok := _u.mutation.SettingsKey(); ok {
		if err := ddnsipsource.SettingsKeyValidator(v); err != nil {
			return &ValidationError{Name: "settings_key", err: fmt.Errorf(`ent: validator failed for field "DDNSIPSource.settings_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := ddnsipsource.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "DDNSIPSource.sort_order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := ddnsipsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "DDNSIPSource.url": %w`, err)}
		}
	}
	return nil
}

func (_u *DDNSIPSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ddnsipsource.Table, ddnsipsource.Columns, sqlgraph.NewFieldSpec(ddnsipsource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SettingsKey(); ok {
		_spec.SetField(ddnsipsource.FieldSettingsKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(ddnsipsource.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(ddnsipsource.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(ddnsipsource.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPType(); ok {
		_spec.SetField(ddnsipsource.FieldIPType, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ddnsipsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DDNSIPSourceUpdateOne is the builder for updating a single DDNSIPSource entity.
type DDNSIPSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DDNSIPSourceMutation
}

// SetSettingsKey sets the "settings_key" field.
func (_u *DDNSIPSourceUpdateOne) SetSettingsKey(v string) *DDNSIPSourceUpdateOne {
	_u.mutation.SetSettingsKey(v)
	return _u
}

// SetNillableSettingsKey sets the "settings_key" field if the given value is not nil.
func (_u *DDNSIPSourceUpdateOne) SetNillableSettingsKey(v *string) *DDNSIPSourceUpdateOne {
	if v != nil {
		_u.SetSettingsKey(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DDNSIPSourceUpdateOne) SetSortOrder(v int) *DDNSIPSourceUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DDNSIPSourceUpdateOne) SetNillableSortOrder(v *int) *DDNSIPSourceUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DDNSIPSourceUpdateOne) AddSortOrder(v int) *DDNSIPSourceUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *DDNSIPSourceUpdateOne) SetURL(v string) *DDNSIPSourceUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *DDNSIPSourceUpdateOne) SetNillableURL(v *string) *DDNSIPSourceUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetIPType sets the "ip_type" field.
func (_u *DDNSIPSourceUpdateOne) SetIPType(v string) *DDNSIPSourceUpdateOne {
	_u.mutation.SetIPType(v)
	return _u
}

// SetNillableIPType sets the "ip_type" field if the given value is not nil.
func (_u *DDNSIPSourceUpdateOne) SetNillableIPType(v *string) *DDNSIPSourceUpdateOne {
	if v != nil {
		_u.SetIPType(*v)
	}
	return _u
}

// Mutation returns the DDNSIPSourceMutation object of the builder.
func (_u *DDNSIPSourceUpdateOne) Mutation() *DDNSIPSourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the DDNSIPSourceUpdate builder.
func (_u *DDNSIPSourceUpdateOne) Where(ps ...predicate.DDNSIPSource) *DDNSIPSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DDNSIPSourceUpdateOne) Select(field string, fields ...string) *DDNSIPSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DDNSIPSource entity.
func (_u *DDNSIPSourceUpdateOne) Save(ctx context.Context) (*DDNSIPSource, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DDNSIPSourceUpdateOne) SaveX(ctx context.Context) *DDNSIPSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DDNSIPSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DDNSIPSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DDNSIPSourceUpdateOne) check() error {
	if v, ok := _u.mutation.SettingsKey(); ok {
		if err := ddnsipsource.SettingsKeyValidator(v); err != nil {
			return &ValidationError{Name: "settings_key", err: fmt.Errorf(`ent: validator failed for field "DDNSIPSource.settings_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := ddnsipsource.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "DDNSIPSource.sort_order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := ddnsipsource.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "DDNSIPSource.url": %w`, err)}
		}
	}
	return nil
}

func (_u *DDNSIPSourceUpdateOne) sqlSave(ctx context.Context) (_node *DDNSIPSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ddnsipsource.Table, ddnsipsource.Columns, sqlgraph.NewFieldSpec(ddnsipsource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DDNSIPSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ddnsipsource.FieldID)
		for _, f := range fields {
			if !ddnsipsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ddnsipsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SettingsKey(); ok {
		_spec.SetField(ddnsipsource.FieldSettingsKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(ddnsipsource.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(ddnsipsource.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(ddnsipsource.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPType(); ok {
		_spec.SetField(ddnsipsource.FieldIPType, field.TypeString, value)
	}
	_node = &DDNSIPSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ddnsipsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
