// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnssetting"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DDNSSettingCreate is the builder for creating a DDNSSetting entity.
type DDNSSettingCreate struct {
	config
	mutation *DDNSSettingMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *DDNSSettingCreate) SetKey(v string) *DDNSSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DDNSSettingCreate) SetEnabled(v bool) *DDNSSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DDNSSettingCreate) SetNillableEnabled(v *bool) *DDNSSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIntervalMins sets the "interval_mins" field.
func (_c *DDNSSettingCreate) SetIntervalMins(v int) *DDNSSettingCreate {
	_c.mutation.SetIntervalMins(v)
	return _c
}

// SetNillableIntervalMins sets the "interval_mins" field if the given value is not nil.
func (_c *DDNSSettingCreate) SetNillableIntervalMins(v *int) *DDNSSettingCreate {
	if v != nil {
		_c.SetIntervalMins(*v)
	}
	return _c
}

// SetOnlyOnChange sets the "only_on_change" field.
func (_c *DDNSSettingCreate) SetOnlyOnChange(v bool) *DDNSSettingCreate {
	_c.mutation.SetOnlyOnChange(v)
	return _c
}

// SetNillableOnlyOnChange sets the "only_on_change" field if the given value is not nil.
func (_c *DDNSSettingCreate) SetNillableOnlyOnChange(v *bool) *DDNSSettingCreate {
	if v != nil {
		_c.SetOnlyOnChange(*v)
	}
	return _c
}

// SetMaxRetries sets the "max_retries" field.
func (_c *DDNSSettingCreate) SetMaxRetries(v int) *DDNSSettingCreate {
	_c.mutation.SetMaxRetries(v)
	return _c
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_c *DDNSSettingCreate) SetNillableMaxRetries(v *int) *DDNSSettingCreate {
	if v != nil {
		_c.SetMaxRetries(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DDNSSettingCreate) SetCreatedAt(v time.Time) *DDNSSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DDNSSettingCreate) SetNillableCreatedAt(v *time.Time) *DDNSSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DDNSSettingCreate) SetUpdatedAt(v time.Time) *DDNSSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DDNSSettingCreate) SetNillableUpdatedAt(v *time.Time) *DDNSSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DDNSSettingMutation object of the builder.
func (_c *DDNSSettingCreate) Mutation() *DDNSSettingMutation {
	return _c.mutation
}

// Save creates the DDNSSetting in the database.
func (_c *DDNSSettingCreate) Save(ctx context.Context) (*DDNSSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DDNSSettingCreate) SaveX(ctx context.Context) *DDNSSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DDNSSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DDNSSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DDNSSettingCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ddnssetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.IntervalMins(); !ok {
		v := ddnssetting.DefaultIntervalMins
		_c.mutation.SetIntervalMins(v)
	}
	if _, ok := _c.mutation.OnlyOnChange(); !ok {
		v := ddnssetting.DefaultOnlyOnChange
		_c.mutation.SetOnlyOnChange(v)
	}
	if _, ok := _c.mutation.MaxRetries(); !ok {
		v := ddnssetting.DefaultMaxRetries
		_c.mutation.SetMaxRetries(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ddnssetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ddnssetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DDNSSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "DDNSSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := ddnssetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "DDNSSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "DDNSSetting.enabled"`)}
	}
	if _, ok := _c.mutation.IntervalMins(); !ok {
		return &ValidationError{Name: "interval_mins", err: errors.New(`ent: missing required field "DDNSSetting.interval_mins"`)}
	}
	if _, ok := _c.mutation.OnlyOnChange(); !ok {
		return &ValidationError{Name: "only_on_change", err: errors.New(`ent: missing required field "DDNSSetting.only_on_change"`)}
	}
	if _, ok := _c.mutation.MaxRetries(); !ok {
		return &ValidationError{Name: "max_retries", err: errors.New(`ent: missing required field "DDNSSetting.max_retries"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DDNSSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DDNSSetting.updated_at"`)}
	}
	return nil
}

func (_c *DDNSSettingCreate) sqlSave(ctx context.Context) (*DDNSSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DDNSSettingCreate) createSpec() (*DDNSSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &DDNSSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ddnssetting.Table, sqlgraph.NewFieldSpec(ddnssetting.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(ddnssetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ddnssetting.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.IntervalMins(); ok {
		_spec.SetField(ddnssetting.FieldIntervalMins, field.TypeInt, value)
		_node.IntervalMins = value
	}
	if value, ok := _c.mutation.OnlyOnChange(); ok {
		_spec.SetField(ddnssetting.FieldOnlyOnChange, field.TypeBool, value)
		_node.OnlyOnChange = value
	}
	if value, ok := _c.mutation.MaxRetries(); ok {
		_spec.SetField(ddnssetting.FieldMaxRetries, field.TypeInt, value)
		_node.MaxRetries = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ddnssetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ddnssetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DDNSSettingCreateBulk is the builder for creating many DDNSSetting entities in bulk.
type DDNSSettingCreateBulk struct {
	config
	err      error
	builders []*DDNSSettingCreate
}

// Save creates the DDNSSetting entities in the database.
func (_c *DDNSSettingCreateBulk) Save(ctx context.Context) ([]*DDNSSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DDNSSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DDNSSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DDNSSettingCreateBulk) SaveX(ctx context.Context) []*DDNSSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DDNSSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DDNSSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
