// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/ddnssetting"
	"cfui/internal/persist/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DDNSSettingUpdate is the builder for updating DDNSSetting entities.
type DDNSSettingUpdate struct {
	config
	hooks    []Hook
	mutation *DDNSSettingMutation
}

// Where appends a list predicates to the DDNSSettingUpdate builder.
func (_u *DDNSSettingUpdate) Where(ps ...predicate.DDNSSetting) *DDNSSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *DDNSSettingUpdate) SetKey(v string) *DDNSSettingUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *DDNSSettingUpdate) SetNillableKey(v *string) *DDNSSettingUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DDNSSettingUpdate) SetEnabled(v bool) *DDNSSettingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DDNSSettingUpdate) SetNillableEnabled(v *bool) *DDNSSettingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalMins sets the "interval_mins" field.
func (_u *DDNSSettingUpdate) SetIntervalMins(v int) *DDNSSettingUpdate {
	_u.mutation.ResetIntervalMins()
	_u.mutation.SetIntervalMins(v)
	return _u
}

// SetNillableIntervalMins sets the "interval_mins" field if the given value is not nil.
func (_u *DDNSSettingUpdate) SetNillableIntervalMins(v *int) *DDNSSettingUpdate {
	if v != nil {
		_u.SetIntervalMins(*v)
	}
	return _u
}

// AddIntervalMins adds value to the "interval_mins" field.
func (_u *DDNSSettingUpdate) AddIntervalMins(v int) *DDNSSettingUpdate {
	_u.mutation.AddIntervalMins(v)
	return _u
}

// SetOnlyOnChange sets the "only_on_change" field.
func (_u *DDNSSettingUpdate) SetOnlyOnChange(v bool) *DDNSSettingUpdate {
	_u.mutation.SetOnlyOnChange(v)
	return _u
}

// SetNillableOnlyOnChange sets the "only_on_change" field if the given value is not nil.
func (_u *DDNSSettingUpdate) SetNillableOnlyOnChange(v *bool) *DDNSSettingUpdate {
	if v != nil {
		_u.SetOnlyOnChange(*v)
	}
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *DDNSSettingUpdate) SetMaxRetries(v int) *DDNSSettingUpdate {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *DDNSSettingUpdate) SetNillableMaxRetries(v *int) *DDNSSettingUpdate {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *DDNSSettingUpdate) AddMaxRetries(v int) *DDNSSettingUpdate {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DDNSSettingUpdate) SetUpdatedAt(v time.Time) *DDNSSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DDNSSettingMutation object of the builder.
func (_u *DDNSSettingUpdate) Mutation() *DDNSSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DDNSSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DDNSSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DDNSSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DDNSSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DDNSSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ddnssetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DDNSSettingUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := ddnssetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "DDNSSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *DDNSSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ddnssetting.Table, ddnssetting.Columns, sqlgraph.NewFieldSpec(ddnssetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(ddnssetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ddnssetting.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalMins(); ok {
		_spec.SetField(ddnssetting.FieldIntervalMins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalMins(); ok {
		_spec.AddField(ddnssetting.FieldIntervalMins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OnlyOnChange(); ok {
		_spec.SetField(ddnssetting.FieldOnlyOnChange, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(ddnssetting.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(ddnssetting.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ddnssetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ddnssetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DDNSSettingUpdateOne is the builder for updating a single DDNSSetting entity.
type DDNSSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DDNSSettingMutation
}

// SetKey sets the "key" field.
func (_u *DDNSSettingUpdateOne) SetKey(v string) *DDNSSettingUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *DDNSSettingUpdateOne) SetNillableKey(v *string) *DDNSSettingUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DDNSSettingUpdateOne) SetEnabled(v bool) *DDNSSettingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DDNSSettingUpdateOne) SetNillableEnabled(v *bool) *DDNSSettingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalMins sets the "interval_mins" field.
func (_u *DDNSSettingUpdateOne) SetIntervalMins(v int) *DDNSSettingUpdateOne {
	_u.mutation.ResetIntervalMins()
	_u.mutation.SetIntervalMins(v)
	return _u
}

// SetNillableIntervalMins sets the "interval_mins" field if the given value is not nil.
func (_u *DDNSSettingUpdateOne) SetNillableIntervalMins(v *int) *DDNSSettingUpdateOne {
	if v != nil {
		_u.SetIntervalMins(*v)
	}
	return _u
}

// AddIntervalMins adds value to the "interval_mins" field.
func (_u *DDNSSettingUpdateOne) AddIntervalMins(v int) *DDNSSettingUpdateOne {
	_u.mutation.AddIntervalMins(v)
	return _u
}

// SetOnlyOnChange sets the "only_on_change" field.
func (_u *DDNSSettingUpdateOne) SetOnlyOnChange(v bool) *DDNSSettingUpdateOne {
	_u.mutation.SetOnlyOnChange(v)
	return _u
}

// SetNillableOnlyOnChange sets the "only_on_change" field if the given value is not nil.
func (_u *DDNSSettingUpdateOne) SetNillableOnlyOnChange(v *bool) *DDNSSettingUpdateOne {
	if v != nil {
		_u.SetOnlyOnChange(*v)
	}
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *DDNSSettingUpdateOne) SetMaxRetries(v int) *DDNSSettingUpdateOne {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *DDNSSettingUpdateOne) SetNillableMaxRetries(v *int) *DDNSSettingUpdateOne {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *DDNSSettingUpdateOne) AddMaxRetries(v int) *DDNSSettingUpdateOne {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DDNSSettingUpdateOne) SetUpdatedAt(v time.Time) *DDNSSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DDNSSettingMutation object of the builder.
func (_u *DDNSSettingUpdateOne) Mutation() *DDNSSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the DDNSSettingUpdate builder.
func (_u *DDNSSettingUpdateOne) Where(ps ...predicate.DDNSSetting) *DDNSSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DDNSSettingUpdateOne) Select(field string, fields ...string) *DDNSSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DDNSSetting entity.
func (_u *DDNSSettingUpdateOne) Save(ctx context.Context) (*DDNSSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DDNSSettingUpdateOne) SaveX(ctx context.Context) *DDNSSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DDNSSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DDNSSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DDNSSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ddnssetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DDNSSettingUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := ddnssetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "DDNSSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *DDNSSettingUpdateOne) sqlSave(ctx context.Context) (_node *DDNSSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ddnssetting.Table, ddnssetting.Columns, sqlgraph.NewFieldSpec(ddnssetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DDNSSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ddnssetting.FieldID)
		for _, f := range fields {
			if !ddnssetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ddnssetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(ddnssetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ddnssetting.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalMins(); ok {
		_spec.SetField(ddnssetting.FieldIntervalMins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalMins(); ok {
		_spec.AddField(ddnssetting.FieldIntervalMins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OnlyOnChange(); ok {
		_spec.SetField(ddnssetting.FieldOnlyOnChange, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(ddnssetting.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(ddnssetting.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ddnssetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DDNSSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ddnssetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
