// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/oauthvalidationreport"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OAuthValidationReport is the model entity for the OAuthValidationReport schema.
type OAuthValidationReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ReportID holds the value of the "report_id" field.
	ReportID string `json:"report_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// SessionLabel holds the value of the "session_label" field.
	SessionLabel string `json:"session_label,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName string `json:"account_name,omitempty"`
	// ZoneID holds the value of the "zone_id" field.
	ZoneID string `json:"zone_id,omitempty"`
	// ZoneName holds the value of the "zone_name" field.
	ZoneName string `json:"zone_name,omitempty"`
	// GeneratedAt holds the value of the "generated_at" field.
	GeneratedAt time.Time `json:"generated_at,omitempty"`
	// SavedAt holds the value of the "saved_at" field.
	SavedAt time.Time `json:"saved_at,omitempty"`
	// ScopeMissing holds the value of the "scope_missing" field.
	ScopeMissing int `json:"scope_missing,omitempty"`
	// APIUnavailable holds the value of the "api_unavailable" field.
	APIUnavailable int `json:"api_unavailable,omitempty"`
	// APIMissingScope holds the value of the "api_missing_scope" field.
	APIMissingScope int `json:"api_missing_scope,omitempty"`
	// ActionItems holds the value of the "action_items" field.
	ActionItems int `json:"action_items,omitempty"`
	// ReportBody holds the value of the "report_body" field.
	ReportBody   string `json:"report_body,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthValidationReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthvalidationreport.FieldID, oauthvalidationreport.FieldScopeMissing, oauthvalidationreport.FieldAPIUnavailable, oauthvalidationreport.FieldAPIMissingScope, oauthvalidationreport.FieldActionItems:
			values[i] = new(sql.NullInt64)
		case oauthvalidationreport.FieldReportID, oauthvalidationreport.FieldSessionID, oauthvalidationreport.FieldSessionLabel, oauthvalidationreport.FieldAccountID, oauthvalidationreport.FieldAccountName, oauthvalidationreport.FieldZoneID, oauthvalidationreport.FieldZoneName, oauthvalidationreport.FieldReportBody:
			values[i] = new(sql.NullString)
		case oauthvalidationreport.FieldGeneratedAt, oauthvalidationreport.FieldSavedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthValidationReport fields.
func (_m *OAuthValidationReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthvalidationreport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case oauthvalidationreport.FieldReportID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field report_id", values[i])
			} else if value.Valid {
				_m.ReportID = value.String
			}
		case oauthvalidationreport.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case oauthvalidationreport.FieldSessionLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_label", values[i])
			} else if value.Valid {
				_m.SessionLabel = value.String
			}
		case oauthvalidationreport.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case oauthvalidationreport.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				_m.AccountName = value.String
			}
		case oauthvalidationreport.FieldZoneID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zone_id", values[i])
			} else if value.Valid {
				_m.ZoneID = value.String
			}
		case oauthvalidationreport.FieldZoneName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zone_name", values[i])
			} else if value.Valid {
				_m.ZoneName = value.String
			}
		case oauthvalidationreport.FieldGeneratedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field generated_at", values[i])
			} else if value.Valid {
				_m.GeneratedAt = value.Time
			}
		case oauthvalidationreport.FieldSavedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field saved_at", values[i])
			} else if value.Valid {
				_m.SavedAt = value.Time
			}
		case oauthvalidationreport.FieldScopeMissing:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scope_missing", values[i])
			} else if value.Valid {
				_m.ScopeMissing = int(value.Int64)
			}
		case oauthvalidationreport.FieldAPIUnavailable:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_unavailable", values[i])
			} else if value.Valid {
				_m.APIUnavailable = int(value.Int64)
			}
		case oauthvalidationreport.FieldAPIMissingScope:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_missing_scope", values[i])
			} else if value.Valid {
				_m.APIMissingScope = int(value.Int64)
			}
		case oauthvalidationreport.FieldActionItems:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field action_items", values[i])
			} else if value.Valid {
				_m.ActionItems = int(value.Int64)
			}
		case oauthvalidationreport.FieldReportBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field report_body", values[i])
			} else if value.Valid {
				_m.ReportBody = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthValidationReport.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthValidationReport) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthValidationReport.
// Note that you need to call OAuthValidationReport.Unwrap() before calling this method if this OAuthValidationReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthValidationReport) Update() *OAuthValidationReportUpdateOne {
	return NewOAuthValidationReportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthValidationReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthValidationReport) Unwrap() *OAuthValidationReport {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthValidationReport is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthValidationReport) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthValidationReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("report_id=")
	builder.WriteString(_m.ReportID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("session_label=")
	builder.WriteString(_m.SessionLabel)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("account_name=")
	builder.WriteString(_m.AccountName)
	builder.WriteString(", ")
	builder.WriteString("zone_id=")
	builder.WriteString(_m.ZoneID)
	builder.WriteString(", ")
	builder.WriteString("zone_name=")
	builder.WriteString(_m.ZoneName)
	builder.WriteString(", ")
	builder.WriteString("generated_at=")
	builder.WriteString(_m.GeneratedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("saved_at=")
	builder.WriteString(_m.SavedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scope_missing=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScopeMissing))
	builder.WriteString(", ")
	builder.WriteString("api_unavailable=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIUnavailable))
	builder.WriteString(", ")
	builder.WriteString("api_missing_scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIMissingScope))
	builder.WriteString(", ")
	builder.WriteString("action_items=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionItems))
	builder.WriteString(", ")
	builder.WriteString("report_body=")
	builder.WriteString(_m.ReportBody)
	builder.WriteByte(')')
	return builder.String()
}

// OAuthValidationReports is a parsable slice of OAuthValidationReport.
type OAuthValidationReports []*OAuthValidationReport
