// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/oauthvalidationreport"
	"cfui/internal/persist/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthValidationReportUpdate is the builder for updating OAuthValidationReport entities.
type OAuthValidationReportUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthValidationReportMutation
}

// Where appends a list predicates to the OAuthValidationReportUpdate builder.
func (_u *OAuthValidationReportUpdate) Where(ps ...predicate.OAuthValidationReport) *OAuthValidationReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReportID sets the "report_id" field.
func (_u *OAuthValidationReportUpdate) SetReportID(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetReportID(v)
	return _u
}

// SetNillableReportID sets the "report_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableReportID(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetReportID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *OAuthValidationReportUpdate) SetSessionID(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableSessionID(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSessionLabel sets the "session_label" field.
func (_u *OAuthValidationReportUpdate) SetSessionLabel(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetSessionLabel(v)
	return _u
}

// SetNillableSessionLabel sets the "session_label" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableSessionLabel(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetSessionLabel(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OAuthValidationReportUpdate) SetAccountID(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableAccountID(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *OAuthValidationReportUpdate) SetAccountName(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableAccountName(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetZoneID sets the "zone_id" field.
func (_u *OAuthValidationReportUpdate) SetZoneID(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetZoneID(v)
	return _u
}

// SetNillableZoneID sets the "zone_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableZoneID(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetZoneID(*v)
	}
	return _u
}

// SetZoneName sets the "zone_name" field.
func (_u *OAuthValidationReportUpdate) SetZoneName(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetZoneName(v)
	return _u
}

// SetNillableZoneName sets the "zone_name" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableZoneName(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetZoneName(*v)
	}
	return _u
}

// SetGeneratedAt sets the "generated_at" field.
func (_u *OAuthValidationReportUpdate) SetGeneratedAt(v time.Time) *OAuthValidationReportUpdate {
	_u.mutation.SetGeneratedAt(v)
	return _u
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableGeneratedAt(v *time.Time) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetGeneratedAt(*v)
	}
	return _u
}

// SetScopeMissing sets the "scope_missing" field.
func (_u *OAuthValidationReportUpdate) SetScopeMissing(v int) *OAuthValidationReportUpdate {
	_u.mutation.ResetScopeMissing()
	_u.mutation.SetScopeMissing(v)
	return _u
}

// SetNillableScopeMissing sets the "scope_missing" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableScopeMissing(v *int) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetScopeMissing(*v)
	}
	return _u
}

// AddScopeMissing adds value to the "scope_missing" field.
func (_u *OAuthValidationReportUpdate) AddScopeMissing(v int) *OAuthValidationReportUpdate {
	_u.mutation.AddScopeMissing(v)
	return _u
}

// SetAPIUnavailable sets the "api_unavailable" field.
func (_u *OAuthValidationReportUpdate) SetAPIUnavailable(v int) *OAuthValidationReportUpdate {
	_u.mutation.ResetAPIUnavailable()
	_u.mutation.SetAPIUnavailable(v)
	return _u
}

// SetNillableAPIUnavailable sets the "api_unavailable" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableAPIUnavailable(v *int) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetAPIUnavailable(*v)
	}
	return _u
}

// AddAPIUnavailable adds value to the "api_unavailable" field.
func (_u *OAuthValidationReportUpdate) AddAPIUnavailable(v int) *OAuthValidationReportUpdate {
	_u.mutation.AddAPIUnavailable(v)
	return _u
}

// SetAPIMissingScope sets the "api_missing_scope" field.
func (_u *OAuthValidationReportUpdate) SetAPIMissingScope(v int) *OAuthValidationReportUpdate {
	_u.mutation.ResetAPIMissingScope()
	_u.mutation.SetAPIMissingScope(v)
	return _u
}

// SetNillableAPIMissingScope sets the "api_missing_scope" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableAPIMissingScope(v *int) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetAPIMissingScope(*v)
	}
	return _u
}

// AddAPIMissingScope adds value to the "api_missing_scope" field.
func (_u *OAuthValidationReportUpdate) AddAPIMissingScope(v int) *OAuthValidationReportUpdate {
	_u.mutation.AddAPIMissingScope(v)
	return _u
}

// SetActionItems sets the "action_items" field.
func (_u *OAuthValidationReportUpdate) SetActionItems(v int) *OAuthValidationReportUpdate {
	_u.mutation.ResetActionItems()
	_u.mutation.SetActionItems(v)
	return _u
}

// SetNillableActionItems sets the "action_items" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableActionItems(v *int) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetActionItems(*v)
	}
	return _u
}

// AddActionItems adds value to the "action_items" field.
func (_u *OAuthValidationReportUpdate) AddActionItems(v int) *OAuthValidationReportUpdate {
	_u.mutation.AddActionItems(v)
	return _u
}

// SetReportBody sets the "report_body" field.
func (_u *OAuthValidationReportUpdate) SetReportBody(v string) *OAuthValidationReportUpdate {
	_u.mutation.SetReportBody(v)
	return _u
}

// SetNillableReportBody sets the "report_body" field if the given value is not nil.
func (_u *OAuthValidationReportUpdate) SetNillableReportBody(v *string) *OAuthValidationReportUpdate {
	if v != nil {
		_u.SetReportBody(*v)
	}
	return _u
}

// Mutation returns the OAuthValidationReportMutation object of the builder.
func (_u *OAuthValidationReportUpdate) Mutation() *OAuthValidationReportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthValidationReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthValidationReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthValidationReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthValidationReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthValidationReportUpdate) check() error {
	if v, ok := _u.mutation.ReportID(); ok {
		if err := oauthvalidationreport.ReportIDValidator(v); err != nil {
			return &ValidationError{Name: "report_id", err: fmt.Errorf(`ent: validator failed for field "OAuthValidationReport.report_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReportBody(); ok {
		if err := oauthvalidationreport.ReportBodyValidator(v); err != nil {
			return &ValidationError{Name: "report_body", err: fmt.Errorf(`ent: validator failed for field "OAuthValidationReport.report_body": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthValidationReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthvalidationreport.Table, oauthvalidationreport.Columns, sqlgraph.NewFieldSpec(oauthvalidationreport.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReportID(); ok {
		_spec.SetField(oauthvalidationreport.FieldReportID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(oauthvalidationreport.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionLabel(); ok {
		_spec.SetField(oauthvalidationreport.FieldSessionLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(oauthvalidationreport.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(oauthvalidationreport.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneID(); ok {
		_spec.SetField(oauthvalidationreport.FieldZoneID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneName(); ok {
		_spec.SetField(oauthvalidationreport.FieldZoneName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GeneratedAt(); ok {
		_spec.SetField(oauthvalidationreport.FieldGeneratedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScopeMissing(); ok {
		_spec.SetField(oauthvalidationreport.FieldScopeMissing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScopeMissing(); ok {
		_spec.AddField(oauthvalidationreport.FieldScopeMissing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIUnavailable(); ok {
		_spec.SetField(oauthvalidationreport.FieldAPIUnavailable, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIUnavailable(); ok {
		_spec.AddField(oauthvalidationreport.FieldAPIUnavailable, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIMissingScope(); ok {
		_spec.SetField(oauthvalidationreport.FieldAPIMissingScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIMissingScope(); ok {
		_spec.AddField(oauthvalidationreport.FieldAPIMissingScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionItems(); ok {
		_spec.SetField(oauthvalidationreport.FieldActionItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActionItems(); ok {
		_spec.AddField(oauthvalidationreport.FieldActionItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReportBody(); ok {
		_spec.SetField(oauthvalidationreport.FieldReportBody, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthvalidationreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthValidationReportUpdateOne is the builder for updating a single OAuthValidationReport entity.
type OAuthValidationReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthValidationReportMutation
}

// SetReportID sets the "report_id" field.
func (_u *OAuthValidationReportUpdateOne) SetReportID(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetReportID(v)
	return _u
}

// SetNillableReportID sets the "report_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableReportID(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetReportID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *OAuthValidationReportUpdateOne) SetSessionID(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableSessionID(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSessionLabel sets the "session_label" field.
func (_u *OAuthValidationReportUpdateOne) SetSessionLabel(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetSessionLabel(v)
	return _u
}

// SetNillableSessionLabel sets the "session_label" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableSessionLabel(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetSessionLabel(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OAuthValidationReportUpdateOne) SetAccountID(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableAccountID(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *OAuthValidationReportUpdateOne) SetAccountName(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableAccountName(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetZoneID sets the "zone_id" field.
func (_u *OAuthValidationReportUpdateOne) SetZoneID(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetZoneID(v)
	return _u
}

// SetNillableZoneID sets the "zone_id" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableZoneID(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetZoneID(*v)
	}
	return _u
}

// SetZoneName sets the "zone_name" field.
func (_u *OAuthValidationReportUpdateOne) SetZoneName(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetZoneName(v)
	return _u
}

// SetNillableZoneName sets the "zone_name" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableZoneName(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetZoneName(*v)
	}
	return _u
}

// SetGeneratedAt sets the "generated_at" field.
func (_u *OAuthValidationReportUpdateOne) SetGeneratedAt(v time.Time) *OAuthValidationReportUpdateOne {
	_u.mutation.SetGeneratedAt(v)
	return _u
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableGeneratedAt(v *time.Time) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetGeneratedAt(*v)
	}
	return _u
}

// SetScopeMissing sets the "scope_missing" field.
func (_u *OAuthValidationReportUpdateOne) SetScopeMissing(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.ResetScopeMissing()
	_u.mutation.SetScopeMissing(v)
	return _u
}

// SetNillableScopeMissing sets the "scope_missing" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableScopeMissing(v *int) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetScopeMissing(*v)
	}
	return _u
}

// AddScopeMissing adds value to the "scope_missing" field.
func (_u *OAuthValidationReportUpdateOne) AddScopeMissing(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.AddScopeMissing(v)
	return _u
}

// SetAPIUnavailable sets the "api_unavailable" field.
func (_u *OAuthValidationReportUpdateOne) SetAPIUnavailable(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.ResetAPIUnavailable()
	_u.mutation.SetAPIUnavailable(v)
	return _u
}

// SetNillableAPIUnavailable sets the "api_unavailable" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableAPIUnavailable(v *int) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetAPIUnavailable(*v)
	}
	return _u
}

// AddAPIUnavailable adds value to the "api_unavailable" field.
func (_u *OAuthValidationReportUpdateOne) AddAPIUnavailable(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.AddAPIUnavailable(v)
	return _u
}

// SetAPIMissingScope sets the "api_missing_scope" field.
func (_u *OAuthValidationReportUpdateOne) SetAPIMissingScope(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.ResetAPIMissingScope()
	_u.mutation.SetAPIMissingScope(v)
	return _u
}

// SetNillableAPIMissingScope sets the "api_missing_scope" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableAPIMissingScope(v *int) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetAPIMissingScope(*v)
	}
	return _u
}

// AddAPIMissingScope adds value to the "api_missing_scope" field.
func (_u *OAuthValidationReportUpdateOne) AddAPIMissingScope(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.AddAPIMissingScope(v)
	return _u
}

// SetActionItems sets the "action_items" field.
func (_u *OAuthValidationReportUpdateOne) SetActionItems(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.ResetActionItems()
	_u.mutation.SetActionItems(v)
	return _u
}

// SetNillableActionItems sets the "action_items" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableActionItems(v *int) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetActionItems(*v)
	}
	return _u
}

// AddActionItems adds value to the "action_items" field.
func (_u *OAuthValidationReportUpdateOne) AddActionItems(v int) *OAuthValidationReportUpdateOne {
	_u.mutation.AddActionItems(v)
	return _u
}

// SetReportBody sets the "report_body" field.
func (_u *OAuthValidationReportUpdateOne) SetReportBody(v string) *OAuthValidationReportUpdateOne {
	_u.mutation.SetReportBody(v)
	return _u
}

// SetNillableReportBody sets the "report_body" field if the given value is not nil.
func (_u *OAuthValidationReportUpdateOne) SetNillableReportBody(v *string) *OAuthValidationReportUpdateOne {
	if v != nil {
		_u.SetReportBody(*v)
	}
	return _u
}

// Mutation returns the OAuthValidationReportMutation object of the builder.
func (_u *OAuthValidationReportUpdateOne) Mutation() *OAuthValidationReportMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthValidationReportUpdate builder.
func (_u *OAuthValidationReportUpdateOne) Where(ps ...predicate.OAuthValidationReport) *OAuthValidationReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthValidationReportUpdateOne) Select(field string, fields ...string) *OAuthValidationReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthValidationReport entity.
func (_u *OAuthValidationReportUpdateOne) Save(ctx context.Context) (*OAuthValidationReport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthValidationReportUpdateOne) SaveX(ctx context.Context) *OAuthValidationReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthValidationReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthValidationReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthValidationReportUpdateOne) check() error {
	if v, ok := _u.mutation.ReportID(); ok {
		if err := oauthvalidationreport.ReportIDValidator(v); err != nil {
			return &ValidationError{Name: "report_id", err: fmt.Errorf(`ent: validator failed for field "OAuthValidationReport.report_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReportBody(); ok {
		if err := oauthvalidationreport.ReportBodyValidator(v); err != nil {
			return &ValidationError{Name: "report_body", err: fmt.Errorf(`ent: validator failed for field "OAuthValidationReport.report_body": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthValidationReportUpdateOne) sqlSave(ctx context.Context) (_node *OAuthValidationReport, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthvalidationreport.Table, oauthvalidationreport.Columns, sqlgraph.NewFieldSpec(oauthvalidationreport.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthValidationReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthvalidationreport.FieldID)
		for _, f := range fields {
			if !oauthvalidationreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthvalidationreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReportID(); ok {
		_spec.SetField(oauthvalidationreport.FieldReportID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(oauthvalidationreport.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionLabel(); ok {
		_spec.SetField(oauthvalidationreport.FieldSessionLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(oauthvalidationreport.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(oauthvalidationreport.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneID(); ok {
		_spec.SetField(oauthvalidationreport.FieldZoneID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZoneName(); ok {
		_spec.SetField(oauthvalidationreport.FieldZoneName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GeneratedAt(); ok {
		_spec.SetField(oauthvalidationreport.FieldGeneratedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScopeMissing(); ok {
		_spec.SetField(oauthvalidationreport.FieldScopeMissing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScopeMissing(); ok {
		_spec.AddField(oauthvalidationreport.FieldScopeMissing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIUnavailable(); ok {
		_spec.SetField(oauthvalidationreport.FieldAPIUnavailable, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIUnavailable(); ok {
		_spec.AddField(oauthvalidationreport.FieldAPIUnavailable, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIMissingScope(); ok {
		_spec.SetField(oauthvalidationreport.FieldAPIMissingScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIMissingScope(); ok {
		_spec.AddField(oauthvalidationreport.FieldAPIMissingScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionItems(); ok {
		_spec.SetField(oauthvalidationreport.FieldActionItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActionItems(); ok {
		_spec.AddField(oauthvalidationreport.FieldActionItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReportBody(); ok {
		_spec.SetField(oauthvalidationreport.FieldReportBody, field.TypeString, value)
	}
	_node = &OAuthValidationReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthvalidationreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
