// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/r2webdavsetting"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// R2WebDAVSetting is the model entity for the R2WebDAVSetting schema.
type R2WebDAVSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// BucketName holds the value of the "bucket_name" field.
	BucketName string `json:"bucket_name,omitempty"`
	// Jurisdiction holds the value of the "jurisdiction" field.
	Jurisdiction string `json:"jurisdiction,omitempty"`
	// WebdavUsername holds the value of the "webdav_username" field.
	WebdavUsername string `json:"webdav_username,omitempty"`
	// WebdavPasswordHash holds the value of the "webdav_password_hash" field.
	WebdavPasswordHash string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*R2WebDAVSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case r2webdavsetting.FieldEnabled:
			values[i] = new(sql.NullBool)
		case r2webdavsetting.FieldID:
			values[i] = new(sql.NullInt64)
		case r2webdavsetting.FieldKey, r2webdavsetting.FieldAccountID, r2webdavsetting.FieldBucketName, r2webdavsetting.FieldJurisdiction, r2webdavsetting.FieldWebdavUsername, r2webdavsetting.FieldWebdavPasswordHash:
			values[i] = new(sql.NullString)
		case r2webdavsetting.FieldCreatedAt, r2webdavsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the R2WebDAVSetting fields.
func (_m *R2WebDAVSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case r2webdavsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case r2webdavsetting.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case r2webdavsetting.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case r2webdavsetting.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case r2webdavsetting.FieldBucketName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_name", values[i])
			} else if value.Valid {
				_m.BucketName = value.String
			}
		case r2webdavsetting.FieldJurisdiction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field jurisdiction", values[i])
			} else if value.Valid {
				_m.Jurisdiction = value.String
			}
		case r2webdavsetting.FieldWebdavUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_username", values[i])
			} else if value.Valid {
				_m.WebdavUsername = value.String
			}
		case r2webdavsetting.FieldWebdavPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webdav_password_hash", values[i])
			} else if value.Valid {
				_m.WebdavPasswordHash = value.String
			}
		case r2webdavsetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case r2webdavsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the R2WebDAVSetting.
// This includes values selected through modifiers, order, etc.
func (_m *R2WebDAVSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this R2WebDAVSetting.
// Note that you need to call R2WebDAVSetting.Unwrap() before calling this method if this R2WebDAVSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *R2WebDAVSetting) Update() *R2WebDAVSettingUpdateOne {
	return NewR2WebDAVSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the R2WebDAVSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *R2WebDAVSetting) Unwrap() *R2WebDAVSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: R2WebDAVSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *R2WebDAVSetting) String() string {
	var builder strings.Builder
	builder.WriteString("R2WebDAVSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("bucket_name=")
	builder.WriteString(_m.BucketName)
	builder.WriteString(", ")
	builder.WriteString("jurisdiction=")
	builder.WriteString(_m.Jurisdiction)
	builder.WriteString(", ")
	builder.WriteString("webdav_username=")
	builder.WriteString(_m.WebdavUsername)
	builder.WriteString(", ")
	builder.WriteString("webdav_password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// R2WebDAVSettings is a parsable slice of R2WebDAVSetting.
type R2WebDAVSettings []*R2WebDAVSetting
