// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/r2webdavsetting"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// R2WebDAVSettingCreate is the builder for creating a R2WebDAVSetting entity.
type R2WebDAVSettingCreate struct {
	config
	mutation *R2WebDAVSettingMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *R2WebDAVSettingCreate) SetKey(v string) *R2WebDAVSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *R2WebDAVSettingCreate) SetEnabled(v bool) *R2WebDAVSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableEnabled(v *bool) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *R2WebDAVSettingCreate) SetAccountID(v string) *R2WebDAVSettingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableAccountID(v *string) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetBucketName sets the "bucket_name" field.
func (_c *R2WebDAVSettingCreate) SetBucketName(v string) *R2WebDAVSettingCreate {
	_c.mutation.SetBucketName(v)
	return _c
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableBucketName(v *string) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetBucketName(*v)
	}
	return _c
}

// SetJurisdiction sets the "jurisdiction" field.
func (_c *R2WebDAVSettingCreate) SetJurisdiction(v string) *R2WebDAVSettingCreate {
	_c.mutation.SetJurisdiction(v)
	return _c
}

// SetNillableJurisdiction sets the "jurisdiction" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableJurisdiction(v *string) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetJurisdiction(*v)
	}
	return _c
}

// SetWebdavUsername sets the "webdav_username" field.
func (_c *R2WebDAVSettingCreate) SetWebdavUsername(v string) *R2WebDAVSettingCreate {
	_c.mutation.SetWebdavUsername(v)
	return _c
}

// SetNillableWebdavUsername sets the "webdav_username" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableWebdavUsername(v *string) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetWebdavUsername(*v)
	}
	return _c
}

// SetWebdavPasswordHash sets the "webdav_password_hash" field.
func (_c *R2WebDAVSettingCreate) SetWebdavPasswordHash(v string) *R2WebDAVSettingCreate {
	_c.mutation.SetWebdavPasswordHash(v)
	return _c
}

// SetNillableWebdavPasswordHash sets the "webdav_password_hash" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableWebdavPasswordHash(v *string) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetWebdavPasswordHash(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *R2WebDAVSettingCreate) SetCreatedAt(v time.Time) *R2WebDAVSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableCreatedAt(v *time.Time) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *R2WebDAVSettingCreate) SetUpdatedAt(v time.Time) *R2WebDAVSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *R2WebDAVSettingCreate) SetNillableUpdatedAt(v *time.Time) *R2WebDAVSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the R2WebDAVSettingMutation object of the builder.
func (_c *R2WebDAVSettingCreate) Mutation() *R2WebDAVSettingMutation {
	return _c.mutation
}

// Save creates the R2WebDAVSetting in the database.
func (_c *R2WebDAVSettingCreate) Save(ctx context.Context) (*R2WebDAVSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *R2WebDAVSettingCreate) SaveX(ctx context.Context) *R2WebDAVSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *R2WebDAVSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *R2WebDAVSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *R2WebDAVSettingCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := r2webdavsetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		v := r2webdavsetting.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.BucketName(); !ok {
		v := r2webdavsetting.DefaultBucketName
		_c.mutation.SetBucketName(v)
	}
	if _, ok := _c.mutation.Jurisdiction(); !ok {
		v := r2webdavsetting.DefaultJurisdiction
		_c.mutation.SetJurisdiction(v)
	}
	if _, ok := _c.mutation.WebdavUsername(); !ok {
		v := r2webdavsetting.DefaultWebdavUsername
		_c.mutation.SetWebdavUsername(v)
	}
	if _, ok := _c.mutation.WebdavPasswordHash(); !ok {
		v := r2webdavsetting.DefaultWebdavPasswordHash
		_c.mutation.SetWebdavPasswordHash(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := r2webdavsetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := r2webdavsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *R2WebDAVSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "R2WebDAVSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := r2webdavsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "R2WebDAVSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "R2WebDAVSetting.enabled"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "R2WebDAVSetting.account_id"`)}
	}
	if _, ok := _c.mutation.BucketName(); !ok {
		return &ValidationError{Name: "bucket_name", err: errors.New(`ent: missing required field "R2WebDAVSetting.bucket_name"`)}
	}
	if _, ok := _c.mutation.Jurisdiction(); !ok {
		return &ValidationError{Name: "jurisdiction", err: errors.New(`ent: missing required field "R2WebDAVSetting.jurisdiction"`)}
	}
	if _, ok := _c.mutation.WebdavUsername(); !ok {
		return &ValidationError{Name: "webdav_username", err: errors.New(`ent: missing required field "R2WebDAVSetting.webdav_username"`)}
	}
	if _, ok := _c.mutation.WebdavPasswordHash(); !ok {
		return &ValidationError{Name: "webdav_password_hash", err: errors.New(`ent: missing required field "R2WebDAVSetting.webdav_password_hash"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "R2WebDAVSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "R2WebDAVSetting.updated_at"`)}
	}
	return nil
}

func (_c *R2WebDAVSettingCreate) sqlSave(ctx context.Context) (*R2WebDAVSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *R2WebDAVSettingCreate) createSpec() (*R2WebDAVSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &R2WebDAVSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(r2webdavsetting.Table, sqlgraph.NewFieldSpec(r2webdavsetting.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(r2webdavsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(r2webdavsetting.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(r2webdavsetting.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.BucketName(); ok {
		_spec.SetField(r2webdavsetting.FieldBucketName, field.TypeString, value)
		_node.BucketName = value
	}
	if value, ok := _c.mutation.Jurisdiction(); ok {
		_spec.SetField(r2webdavsetting.FieldJurisdiction, field.TypeString, value)
		_node.Jurisdiction = value
	}
	if value, ok := _c.mutation.WebdavUsername(); ok {
		_spec.SetField(r2webdavsetting.FieldWebdavUsername, field.TypeString, value)
		_node.WebdavUsername = value
	}
	if value, ok := _c.mutation.WebdavPasswordHash(); ok {
		_spec.SetField(r2webdavsetting.FieldWebdavPasswordHash, field.TypeString, value)
		_node.WebdavPasswordHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(r2webdavsetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(r2webdavsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// R2WebDAVSettingCreateBulk is the builder for creating many R2WebDAVSetting entities in bulk.
type R2WebDAVSettingCreateBulk struct {
	config
	err      error
	builders []*R2WebDAVSettingCreate
}

// Save creates the R2WebDAVSetting entities in the database.
func (_c *R2WebDAVSettingCreateBulk) Save(ctx context.Context) ([]*R2WebDAVSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*R2WebDAVSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*R2WebDAVSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *R2WebDAVSettingCreateBulk) SaveX(ctx context.Context) []*R2WebDAVSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *R2WebDAVSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *R2WebDAVSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
