// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/predicate"
	"cfui/internal/persist/ent/r2webdavsetting"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// R2WebDAVSettingDelete is the builder for deleting a R2WebDAVSetting entity.
type R2WebDAVSettingDelete struct {
	config
	hooks    []Hook
	mutation *R2WebDAVSettingMutation
}

// Where appends a list predicates to the R2WebDAVSettingDelete builder.
func (_d *R2WebDAVSettingDelete) Where(ps ...predicate.R2WebDAVSetting) *R2WebDAVSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *R2WebDAVSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *R2WebDAVSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *R2WebDAVSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(r2webdavsetting.Table, sqlgraph.NewFieldSpec(r2webdavsetting.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// R2WebDAVSettingDeleteOne is the builder for deleting a single R2WebDAVSetting entity.
type R2WebDAVSettingDeleteOne struct {
	_d *R2WebDAVSettingDelete
}

// Where appends a list predicates to the R2WebDAVSettingDelete builder.
func (_d *R2WebDAVSettingDeleteOne) Where(ps ...predicate.R2WebDAVSetting) *R2WebDAVSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *R2WebDAVSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{r2webdavsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *R2WebDAVSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
