// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/predicate"
	"cfui/internal/persist/ent/s3webdavsetting"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// S3WebDAVSettingDelete is the builder for deleting a S3WebDAVSetting entity.
type S3WebDAVSettingDelete struct {
	config
	hooks    []Hook
	mutation *S3WebDAVSettingMutation
}

// Where appends a list predicates to the S3WebDAVSettingDelete builder.
func (_d *S3WebDAVSettingDelete) Where(ps ...predicate.S3WebDAVSetting) *S3WebDAVSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *S3WebDAVSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *S3WebDAVSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *S3WebDAVSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(s3webdavsetting.Table, sqlgraph.NewFieldSpec(s3webdavsetting.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// S3WebDAVSettingDeleteOne is the builder for deleting a single S3WebDAVSetting entity.
type S3WebDAVSettingDeleteOne struct {
	_d *S3WebDAVSettingDelete
}

// Where appends a list predicates to the S3WebDAVSettingDelete builder.
func (_d *S3WebDAVSettingDeleteOne) Where(ps ...predicate.S3WebDAVSetting) *S3WebDAVSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *S3WebDAVSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{s3webdavsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *S3WebDAVSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
