// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/predicate"
	"cfui/internal/persist/ent/tunnelmanagement"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelManagementUpdate is the builder for updating TunnelManagement entities.
type TunnelManagementUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelManagementMutation
}

// Where appends a list predicates to the TunnelManagementUpdate builder.
func (_u *TunnelManagementUpdate) Where(ps ...predicate.TunnelManagement) *TunnelManagementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *TunnelManagementUpdate) SetKey(v string) *TunnelManagementUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableKey(v *string) *TunnelManagementUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TunnelManagementUpdate) SetEnabled(v bool) *TunnelManagementUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableEnabled(v *bool) *TunnelManagementUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TunnelManagementUpdate) SetAccountID(v string) *TunnelManagementUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableAccountID(v *string) *TunnelManagementUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelManagementUpdate) SetTunnelID(v string) *TunnelManagementUpdate {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableTunnelID(v *string) *TunnelManagementUpdate {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetAPIToken sets the "api_token" field.
func (_u *TunnelManagementUpdate) SetAPIToken(v string) *TunnelManagementUpdate {
	_u.mutation.SetAPIToken(v)
	return _u
}

// SetNillableAPIToken sets the "api_token" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableAPIToken(v *string) *TunnelManagementUpdate {
	if v != nil {
		_u.SetAPIToken(*v)
	}
	return _u
}

// SetAPIEmail sets the "api_email" field.
func (_u *TunnelManagementUpdate) SetAPIEmail(v string) *TunnelManagementUpdate {
	_u.mutation.SetAPIEmail(v)
	return _u
}

// SetNillableAPIEmail sets the "api_email" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableAPIEmail(v *string) *TunnelManagementUpdate {
	if v != nil {
		_u.SetAPIEmail(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *TunnelManagementUpdate) SetAPIKey(v string) *TunnelManagementUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *TunnelManagementUpdate) SetNillableAPIKey(v *string) *TunnelManagementUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelManagementUpdate) SetUpdatedAt(v time.Time) *TunnelManagementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TunnelManagementMutation object of the builder.
func (_u *TunnelManagementUpdate) Mutation() *TunnelManagementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelManagementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelManagementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelManagementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelManagementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelManagementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunnelmanagement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelManagementUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tunnelmanagement.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelManagement.key": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelManagementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnelmanagement.Table, tunnelmanagement.Columns, sqlgraph.NewFieldSpec(tunnelmanagement.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tunnelmanagement.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tunnelmanagement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(tunnelmanagement.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TunnelID(); ok {
		_spec.SetField(tunnelmanagement.FieldTunnelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIToken(); ok {
		_spec.SetField(tunnelmanagement.FieldAPIToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIEmail(); ok {
		_spec.SetField(tunnelmanagement.FieldAPIEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(tunnelmanagement.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnelmanagement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnelmanagement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelManagementUpdateOne is the builder for updating a single TunnelManagement entity.
type TunnelManagementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelManagementMutation
}

// SetKey sets the "key" field.
func (_u *TunnelManagementUpdateOne) SetKey(v string) *TunnelManagementUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableKey(v *string) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TunnelManagementUpdateOne) SetEnabled(v bool) *TunnelManagementUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableEnabled(v *bool) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TunnelManagementUpdateOne) SetAccountID(v string) *TunnelManagementUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableAccountID(v *string) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetTunnelID sets the "tunnel_id" field.
func (_u *TunnelManagementUpdateOne) SetTunnelID(v string) *TunnelManagementUpdateOne {
	_u.mutation.SetTunnelID(v)
	return _u
}

// SetNillableTunnelID sets the "tunnel_id" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableTunnelID(v *string) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetTunnelID(*v)
	}
	return _u
}

// SetAPIToken sets the "api_token" field.
func (_u *TunnelManagementUpdateOne) SetAPIToken(v string) *TunnelManagementUpdateOne {
	_u.mutation.SetAPIToken(v)
	return _u
}

// SetNillableAPIToken sets the "api_token" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableAPIToken(v *string) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetAPIToken(*v)
	}
	return _u
}

// SetAPIEmail sets the "api_email" field.
func (_u *TunnelManagementUpdateOne) SetAPIEmail(v string) *TunnelManagementUpdateOne {
	_u.mutation.SetAPIEmail(v)
	return _u
}

// SetNillableAPIEmail sets the "api_email" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableAPIEmail(v *string) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetAPIEmail(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *TunnelManagementUpdateOne) SetAPIKey(v string) *TunnelManagementUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *TunnelManagementUpdateOne) SetNillableAPIKey(v *string) *TunnelManagementUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelManagementUpdateOne) SetUpdatedAt(v time.Time) *TunnelManagementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TunnelManagementMutation object of the builder.
func (_u *TunnelManagementUpdateOne) Mutation() *TunnelManagementMutation {
	return _u.mutation
}

// Where appends a list predicates to the TunnelManagementUpdate builder.
func (_u *TunnelManagementUpdateOne) Where(ps ...predicate.TunnelManagement) *TunnelManagementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelManagementUpdateOne) Select(field string, fields ...string) *TunnelManagementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TunnelManagement entity.
func (_u *TunnelManagementUpdateOne) Save(ctx context.Context) (*TunnelManagement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelManagementUpdateOne) SaveX(ctx context.Context) *TunnelManagement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelManagementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelManagementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelManagementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunnelmanagement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelManagementUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tunnelmanagement.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelManagement.key": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelManagementUpdateOne) sqlSave(ctx context.Context) (_node *TunnelManagement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnelmanagement.Table, tunnelmanagement.Columns, sqlgraph.NewFieldSpec(tunnelmanagement.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TunnelManagement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnelmanagement.FieldID)
		for _, f := range fields {
			if !tunnelmanagement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunnelmanagement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tunnelmanagement.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(tunnelmanagement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(tunnelmanagement.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TunnelID(); ok {
		_spec.SetField(tunnelmanagement.FieldTunnelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIToken(); ok {
		_spec.SetField(tunnelmanagement.FieldAPIToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIEmail(); ok {
		_spec.SetField(tunnelmanagement.FieldAPIEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(tunnelmanagement.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunnelmanagement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TunnelManagement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnelmanagement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
