// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cfui/internal/persist/ent/predicate"
	"cfui/internal/persist/ent/tunneltoken"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelTokenUpdate is the builder for updating TunnelToken entities.
type TunnelTokenUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelTokenMutation
}

// Where appends a list predicates to the TunnelTokenUpdate builder.
func (_u *TunnelTokenUpdate) Where(ps ...predicate.TunnelToken) *TunnelTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *TunnelTokenUpdate) SetKey(v string) *TunnelTokenUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TunnelTokenUpdate) SetNillableKey(v *string) *TunnelTokenUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TunnelTokenUpdate) SetToken(v string) *TunnelTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TunnelTokenUpdate) SetNillableToken(v *string) *TunnelTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelTokenUpdate) SetUpdatedAt(v time.Time) *TunnelTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TunnelTokenMutation object of the builder.
func (_u *TunnelTokenUpdate) Mutation() *TunnelTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunneltoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelTokenUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tunneltoken.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelToken.key": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunneltoken.Table, tunneltoken.Columns, sqlgraph.NewFieldSpec(tunneltoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tunneltoken.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tunneltoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunneltoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunneltoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelTokenUpdateOne is the builder for updating a single TunnelToken entity.
type TunnelTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelTokenMutation
}

// SetKey sets the "key" field.
func (_u *TunnelTokenUpdateOne) SetKey(v string) *TunnelTokenUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *TunnelTokenUpdateOne) SetNillableKey(v *string) *TunnelTokenUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TunnelTokenUpdateOne) SetToken(v string) *TunnelTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TunnelTokenUpdateOne) SetNillableToken(v *string) *TunnelTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TunnelTokenUpdateOne) SetUpdatedAt(v time.Time) *TunnelTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TunnelTokenMutation object of the builder.
func (_u *TunnelTokenUpdateOne) Mutation() *TunnelTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the TunnelTokenUpdate builder.
func (_u *TunnelTokenUpdateOne) Where(ps ...predicate.TunnelToken) *TunnelTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelTokenUpdateOne) Select(field string, fields ...string) *TunnelTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TunnelToken entity.
func (_u *TunnelTokenUpdateOne) Save(ctx context.Context) (*TunnelToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelTokenUpdateOne) SaveX(ctx context.Context) *TunnelToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TunnelTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tunneltoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := tunneltoken.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "TunnelToken.key": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelTokenUpdateOne) sqlSave(ctx context.Context) (_node *TunnelToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunneltoken.Table, tunneltoken.Columns, sqlgraph.NewFieldSpec(tunneltoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TunnelToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunneltoken.FieldID)
		for _, f := range fields {
			if !tunneltoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunneltoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(tunneltoken.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tunneltoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tunneltoken.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TunnelToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunneltoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
